#+TITLE:       How to read a book
#+AUTHOR:      Kyle Three Stones
#+DATE:        [2017-12-07 星期四]
#+EMAIL:       kyleemail@163.com
#+OPTIONS:     H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t f:t TeX:t
#+TAGS:        read book
#+CATEGORIES:  book


* HOW TO READ A BOOK
** 第一篇 阅读的层次
*** 第一章 阅读的活力与艺术
书是写给那些想要把读书的主要目的当作是增进理解能力的人而写。
“readers”：那些今天仍然习惯于从书写文字中汲取大量资讯，以增进对世界的了解的人，就和过去历史上每一个深有教养、智慧的人别无
二致。
许多资讯与知识是从口传或观察而得，或者收音机、电视、网络等，但这些是远远不够的，他们知道还得阅读，而他们也真的身体力行。
新时代的传播媒体是否真能增进我们对自己世界的了解？------我们为了理解一件事，并不需要知道和这件事相关的所有事情。太多的资
讯就如太少的资讯一样，都是一种对理解力的阻碍。换句话说，现代媒体正在以压倒性的泛滥资讯阻碍了我们的理解力。
现代媒体经过太精心的设计，直接将包装后的观点装进自己的脑海中，目的都在让人很容易整理出“自己”的思绪，使得思想形同没有需要
了；但事实并非如此。
**** 主动的阅读
目标：
+ 提醒读者，阅读可以是一件多么主动的事
+ 阅读越主动，效果越好
听众或读者的“接收”，应该像棒球赛中的捕手一样，而不是类似被打了一拳，或者得到一项遗产。捕手的艺术就在能接住任何球的技巧：
快速球、曲线球、变化球、慢速球等等。阅读的艺术也在尽可能掌握住每一种讯息的技巧。
同样的书一个人比另一个人读的好：
+ 这人读的更主动
+ 他在阅读中的每一种活动都参与了更多的技巧
阅读是一个复杂的活动，就像写作一样，包含了大量不同的活动。要达成良好的阅读，这些活动都是不可或缺的。一个人越能运作这些活
动，阅读的效果就越好。
**** 阅读的目标：为获得资讯而读以及为求得理解而读
真正的阅读：没有任何外力的帮助，你就是要读这本书。你什么都没有，只凭着内心的力量，玩味着眼前的字句，慢慢地提升自己，从只
有模糊的概念到更清楚地理解为止。
阅读的定义：这是一个凭借着头脑运作，除了玩味读物中的一些字句之外，不假任何外助，以一己之力来提升自我的过程。
凭着自己的心智活动努力阅读，从只有粗浅的了解推进到深入的体会，就像是自我的破茧而出。
这里的“学习”指的是理解更多的事情，而不是记住更多的资讯。
任何一个可以阅读的人，都有能力用这样的方式来阅读。只要我们努力运用这些技巧在有益的读物上，每个人都能读的更好，学的更多，
毫无例外。
**** 阅读就是学习：指导型的学习，以及自我发现型的学习之间的差异
所谓吸收咨询，就是知道某件事发生了；想要被启发，就是要去理解，搞清楚这到底是怎么回事：为什么会发生，与其他的事实有什么关
联，有什么类似的情况，同类的差异在哪里等等。
要能被启发，除了知道作者所说的话之外，还要明白他的意思，懂得他为什么这么说。
蒙田说：初学者的物质在于未学，而学者的无知在于学后。------第二种无知是读错了许多书，总有一群书呆子读得太广，却读不通，被
称为“半瓶醋”（Sophomores）
自我发现型的学习是必要的---这是经由研究、调查或无人指导的状况下，自己深思熟虑的一种学习过程。
“辅导型的自我发现学习”：类似医生努力为病人做许多事，但最终的结论是这个病人必须自己好起来，变得健康起来；农夫为他的植物或
动物做了许多事，结果是这些植物必须长大，变得更好；老师用尽了方法来教学生，学生却必须自己能学习才行。当他学习到了，只是就
会在他的脑海中生根发芽。
无论那种学习方式，都不该没有活力，就像任何阅读都不该死气沉沉。
辅助型自我发现学习及非辅助型自我发现学习之间的差异---一个最基本的不同点就在学习者所使用的教材上。辅助型自我发现学习是阅
读自我或世界的学习；非辅助型学习是阅读一本书，包括倾听，从讲解中学习的一种艺术。
“思考”是指运用我们的头脑去增加知识或理解力。思考是在这两种学习中都会出现的东西，在阅读与倾听时我们必须思考，就像我们在研
究时一定要思考一样。
思考是主动阅读的一部分，还必须观察、记忆，在看不见的地方运用想象力。
阅读的艺术包括了所有非辅助型自我发现学习的技巧：敏锐的观察、灵敏可靠的记忆、想象的空间，再者就是训练有素的分析、省思能力。
因为阅读是一种经过帮助后的发现。
**** 老师的出席与缺席
如果你问一本书一个问题，你就必须自己回答这个问题。只有在你自己作了思考与分析之后，才会在书本上找到答案。因此我们就要懂得
如何让书本来教导我们。
*** 第二章 阅读的层次
+ 读者要追求的目的决定会决定他阅读的技巧；
+ 阅读的效果取决于他在阅读上花了多少努力与技巧。
**** 基础阅读---elementary reading
这个阶段面对的主要问题：如何认出一页中的一个个字
不论我们身为有多精通这样的阅读技巧，我们在阅读的时候还是一直会碰上这个层次的阅读问题。
典型问题：这个句子在说什么？
**** 检视阅读---inspectional reading
特点在强调时间：必须在规定的时间内完成阅读
检视阅读是系统化略读（skimming systematically）的一门艺术
典型问题：这本书在谈什么？
许多优秀的读者都忽略了检视阅读的价值。
**** 分析阅读---analytical reading
一个分析阅读着一定会对自己所读的东西提出许多有系统的问题。
分析阅读就是特别在追寻理解的；分析阅读永远是一种专注的活动；读者会紧抓住一本书，一直读到这本书成为他自己的为止；分析阅读
就是要咀嚼消化一本书。
**** 主题阅读---syntopical reading
需要读者阅读很多书，并列举出这些书之间的相关之处，且能架构出一个可能在哪一本书里都没有提过的主题分析。
主题阅读是最主动、也最花费力气的一种阅读；但确是所有阅读活动中左右收获的，所以绝对值得你努力学习如何做到这样的阅读。
*** 第三章 阅读的第一个层次：基础阅读
**** 基础阅读
在阅读每一位作者的作品时要相当顺手，用不着停下来检查许多生字的意思，也不会被文法或者文章的结构阻碍住。虽然不见得要每句每
字都读得透彻，但你已经能掌握主要句子与章节的意义了。
只有当他能自己阅读时，才能够自己开始学习，也只有这样他才能变成一个真正的阅读高手。
**** 更高层次的阅读
一个人文素养优良的高中，就算什么也没做，也该培养出能够分析阅读的读者。一个优秀的大学，就算什么也没有贡献，也该培育出进行
主题阅读的读者。
*** 第四章 阅读的第二个层次：检视阅读
阅读的层次是渐进积累的：基础阅读包含在检视阅读中，监视阅读又包含在分析阅读中，分析阅读则包含在主题阅读中。
**** 检视阅读
检视阅读分两种：有系统的略读或粗读，粗浅的阅读。有经验的阅读者已经学会同时运用这两个步骤。
检视阅读的两个方式都需要快速的阅读。一个熟练的检视阅读这想要读一本书时，不论碰到多难读或者多长的书，都能够很快的运用这两
种方式读完。
检视阅读在主题阅读中占有非常重要的角色。
***** 有系统的略读或粗读
你花在略读这本书上的时间绝没有浪费
****** 目的：
帮助你决定一本书是否值得一读，以及从基本架构上先找到一些想法。
****** 步骤
1) 先看书名，然后如果有序就先看序
很快看过去。在脑海中将这本书归类为某个特定的类型，在那个类型中，已经包含了哪些书。
2) 研究目录页
对这本书的基本架构做概括性的理解。就像是出发旅行之前，要先看一下地图一样。目录纲要还是很有价值的，在你开始阅读整本书之前，
你应该先仔细阅读目录才对。
3) 如果书中附有索引，也要监视一下
用于快速评估一下这本书涵盖了哪些议题的范围。如果发现列举出来的哪一条词汇很重要，至少看一下引用该词汇的那几页。
4) 读出版社的介绍
许多宣传文案都是作者在出版公司企宣部门的协助下亲自写就的，作者会尽力将书中的主旨正确的摘要出来。
至此，你已经有足够的咨询来判断该书是否值得一读。
5) 挑几个看来跟主旨息息相关的篇章来看
如果这些篇章的开通或结尾有摘要说明，就要仔细阅读这些说明。
6) 最后一步，把书打开，东翻翻西翻翻，念个一两段，有时候连续读几页，但不要太多
最终要的是，不要忽略书做后的两三页，一般作者都会在这里将认为即新又重要的观点重新整理一遍。
现在，在花了几分钟，最多不过一小时的时间内，你对这本书已经了解了很多了。
PS：这是一种非常主动的阅读。一个人如果不够灵活，不能够集中精神来阅读，就没法进行监视阅读。有多少次你在看一本书好书的时候，
翻了好几页，脑海却陷入了白日梦的状态中，等清醒过来，竟完全不明白自己刚才看的那几页在说些什么？如果遵循上述步骤就不会发生
这样的事，因为你始终有一个可以遵循作者思路的系统了。
你可以把自己想象成一名侦探，在找寻一本书的主题或思路的线索；随时保持敏捷，就很容易让一切状况清楚。
***** 粗浅的阅读
头一次面对一本难读的书的时候，从头到尾先读一遍，碰到不懂的地方不要停下来查询或思索。
只注意你能理解的部分，不要为一些没法理解了解的东西而停顿。继续读下去，略过那些不懂的部分，很快你会读到你看的懂的地方。集
中精神在这个部分，继续读下去，将全书读完。这样就算你之理解了50%或者更少，当你读第二遍的时候，都能帮助你理解第一遍略读的
部分；就算不重读，对一本难度很高的书籍了解一半也是很不错的。如果一碰上困难就停住，最后就可能对这本书真的一无所知了。我们
经常被教导，遇到不懂的要去查字典、查资料，但是时候不到就做这些事，却只会妨碍我们的阅读，而非帮助。譬如，阅读莎士比亚的戏
剧会获得极大的快乐。但是一代代高中生被逼着要一幕幕的念，一个生字一个生字的查、一个注脚一个注脚的读，这种快乐就被破坏了，
等他们读到最后的时候，已经忘了开始是什么，也无法洞察全剧的意义了。
比如，去阅读亚当.斯密的国富论，你努力了解那些细微的重点时，企图了解每一个字句，就会错过斯密说的那么清楚的一些大原则。
**** 阅读的速度
阅读速度不是一味的求快，应该是依照读物的性质与复杂程度，用不同的速度来阅读。慢不该慢到值得，快不该快到有损于理解。
理想上，阅读速度不只是能读的快，还要能用不同的速度来阅读，要知道什么时候用什么样的速度是恰当的。
每一本书，不论是多么难读的书，在无关紧要的间隙部分都应该读快一点。
***** 逗留与倒退
拍摄下来的眼睛在活动时的影片，显示年轻或未受过训练的阅读者，在阅读一行字的时候会在五六个地方发生“逗留(fixate)”现象，他们
眼睛在移动时看不见，只有停下来才能看见。因此，他们在读一行的时候，只能间隔着看到一个个单字或者最多两三个字的组合。甚至有
人在读过两三行后又“倒退(regress)”到之前的行上。这些习惯不但浪费而且显然降低了阅读速度。
我们的头脑跟眼睛不一样，并不需要一次只“读”一个字或一个句子。我们的头脑是个惊人的工具，可以在“一瞥”之间掌握一个句子或段落，
只要我们的眼睛提供足够的咨询。
矫正这个喜欢也很容易，利用双手训练自己的眼睛，将大拇指与食指、中指合并在一起，强迫自己的眼睛跟着手部的动作移动。慢慢增快
手的速度，等到你发觉以前，你的速度已经可以比以前快两三倍了。
***** 理解的问题
我们的手就像个计时器，不只负责增进你的阅读速度，也能帮助你专注于你所阅读的东西上。一个优秀的读者就是得读得很主动，很专心。
但分析阅读是想要理解一本书的基本条件。
*** 第五章 如何做一个自我要求的读者
在读书时是保持清醒还是昏昏欲睡，主要看你的阅读目标。如果你想获得利益，你就得保持清醒，也就是尽可能的保持主动，同时还要做
一番努力。做一个自我要求的读者，集中精神在所做的事情上，从而真正的阅读手中的那本书。
在读一本书时打瞌睡，并不是不想努力，而是因为他们不知道如何努力。起身去阅读那些好书，并不是起身让你疲倦，而是因为你欠缺有
效运用自我提升的技巧，在挫败中产生了沮丧，因而才感到厌倦。
**** 主动阅读的基础：一个阅读者要提出的四个基本问题
主动阅读的核心：在阅读时要提出问题来，并且在阅读的过程中，你自己必须尝试去回答。
这是绝对不可忘记的原则，也是自我要求的读者与没有自我要求的读者，有天壤之别的原因。要以适当的顺序提出适当的问题。
1) 整体来说，这本书到底在谈些什么？
找到本书的主题，作者如何依次发展这个主题，如何从核心主题依次分解出从属主题来。
2) 作者细部说了什么，怎么说的？
找出主要的想法、声明与论点，这些组合成作者想要传达的特殊信息。
3) 这本书说得有道理吗？是全部有道理还是部分有道理？
在此之前必须先回答前两个问题，等你了解了一本书，你有责任为这本书做个自己的判断
4) 这本书跟你有什么关系？
如果这本书给了你一些资讯，你一定要问问这些资讯有什么意义。为什么这位作者会认为知道这件事很重要？你真的有必要去了解吗？如
果这本书不只是提供了资讯，还启发了你，就更有必要找出其他相关的，更深的含义或建议，以获得更多的启示。
***** 四个问题的性质
这四个问题概括了一个阅读着的责任。这个原则适合任何一本读物--一本书、一篇文章，甚至一个广告。检视阅读有助于回答前两个问题
，且只有回答了后两个问题才算真的完成了分析阅读，尤其是最后一个问题，可能是主题阅读中最重要的一个问题。
还要知道如何精准、正确的回答问题。养成提出问题、回答问题的习惯，如此训练而来的能力就是阅读的艺术。
**** 如何让一本书真正属于你自己
付钱购买一本书是真正拥有一本书的前凑而已，要真正完全拥有一本书，必须把这本书变成你自己的一本分才行，最好的方法就是写下来。
***** 为什么在书上做笔记不可或缺
1) 那会让你保持清醒
不只是不昏睡，还是非常清醒
2) 主动的阅读是一种思考，而思考倾向于用语言表达出来
一个人如果说他知道他在想什么却说不出来，通常是他其实并不知道自己在想些什么。
3) 将你的感想写下来，能帮助你记住作者的思路
表达你跟作者之间相同或相异的观点，这是你对作者所能付出的最高敬意。
***** 做笔记的方法
+ 画底线
+ 在画底线处的栏外再加画一道线---大括号
+ 在空白处做星号或其他符号---要慎用，之用来强调书中十来个最重要的声明或段落即可
+ 在空白处编号---用于理清作者的论述
+ 在空白处记下其他的页码---表示书中其他部分有相同或相关的要点，可以用Cf标记，表示比较或参照的意思
+ 将关键字或句子圈出来---同画底线
+ 在书页的空白处做笔记---问题的答案、复杂的论点、主要论点发展顺序等
书前的空白页最好用来记载你的思想。在做后的空白页写下个人索引，将作者的主要观点依序记下来，再返回前面的空白页，试着将全书
的大纲写出来，全书的整体架构，列出基本大纲与前后篇章秩序。表现出你在智力上对这本书的所有权。
**** 三种类型的笔记
***** 结构笔记（structural note-making）
检视阅读中要回答问题：
1) 这是什么样的一本书？
2) 整本书在谈的是什么？
3) 作者是借着怎样的整体架构，来发展他的观点或陈述他对这个主题的理解？
做这些笔记做好的地方就是目录页或书名页，之前的笔记没有用到的地方。笔记的重点是全书的架构而不是内容。
***** 概念笔记（conceptual note-making）
代表作者观点的概念；当你读得越深越广时，便也会出现你自己的观点。
主题阅读时，概念笔记除了包含本书的页码还应该包含其他书的页码。
***** 辩证笔记（dialectical note-making）
针对一场讨论情境的笔记，这场讨论由你组织让许多作者一起参与，虽然他们自己并不知道在参与。
通常需要用单独的一张纸来记载。
**** 培养正确阅读的习惯
所谓艺术或技巧，只属于那个能养成习惯，而且依照规则来运作的人。这也是艺术家或任何领域的工匠与众不同之处。
***** 方法
要养成习惯，除了不断的运作练习之外，别无他法。这也是我们通常所说的，从实际去做中学习到如何去做的道理（learn by do）。
***** 习惯是第二天性
经过练习后，你就会比原来做的好的多，就是熟能生巧，像自然天生一样，这也是为什么说习惯是第二天性的道理。
***** 知道一项艺术的规则，跟养成习惯是不同的
我们谈到一个有技术的人时，并不是在说他知道如何去做那件事，而是他已经养成去做那件事的习惯了。
艺术跟其他有规则可循的事一样，是可以学习、运作的。就跟养成其他事情的习惯一样，只要照着规则练习，就可以培养出习惯来。
***** 由许多规则养成一个习惯
阅读就像滑雪一样，像一个专家在做的时候，滑雪跟阅读一样都是很优美又和谐的一种运动。
滑雪教练滑出的优美动作是他口中所说的简单动作，而对一个初学者来说不只是天方夜谭，更近乎侮辱了。你要怎样才能记住教练所说的
每一个动作？屈膝，眼睛往下面山丘看，重心向下，保持背部挺直，还得学者身体前倾。要求似乎没完没了---你怎能记住这么多事项，
同时还要滑雪呢？
你一定要学会忘掉那些分开的步骤，才能表现出整体的动作，而每一个单一的步骤都还要确实表现的很好。但是为了要忘掉这些单一的动
作，一开始你必须先学会每一个单一的动作。达到一个程度时，每个分开的相关动作自然会压缩、连接起来，变成一个完整的动作。一开
始学习者只会注意到自己与那些分开来的动作，等所有分开的动作不再分离，渐渐融为一体时，学习者便将注意力转移到目标上，而他也
具备了要达成目标的能力了。只有这样，你才能将所有动作连结起来，变成一个优秀的滑雪高手。
这是学习一种复杂技术的基本知识。要学习做一个很好的阅读者并不容易，比滑雪复杂多了，其更是一种心智的活动。
** 第二篇 阅读的第三个层次：分析阅读
*** 第六章 一本书的分类（规则一）
**** 书籍分类的重要性
分辨小说和非小说、论说性和非论说性小说一样并非易事。论说性的书主要目的在传达知识，我们要知道的不只是哪一类书籍带给我们指
导，还要知道是用什么样的方法指导，因为不同类型的书，比如历史和哲学，所提供的知识与启发方式就截然不同。
书籍的分类可以通过检视阅读：读读书名、副标题、目录、序言、摘要介绍、索引、宣传文案来了解。
**** 从一本书的书名你能学到什么
阅读书名，可以让阅读者在开始阅读之前，获得一些基本的咨询。事实上只有少之又少的人真的用心读过书名，也想过其中的含义。作者
通常会将书的内容反映在书名中。
阅读书名很重要，但还不够。除非你能在心中有一个分类标准，否则世上再清楚的书名，再详尽的目录、前言，对你也没什么帮助。
只有当你在不同的书籍之间能找出区别，并且定出一些合理又经得起时间考验的分类时，这个规则才会更简单明白一些。
| 分类   |      |
|--------+------|
| 小说   |      |
|        |      |
| 论说类 |      |
|        | 历史 |
|        | 哲学 |
|        | 科学 |
|        | 数学 |
**** 实用性 VS. 理论性作品
任何一本指南的书都是实用的。任何一本书告诉你要该做什么，或如何去做，都是实用的书。

明智的行动就是来自知识。
要让知识变成实用，就要有操作规范。我们一定要超越“知道这是怎么回事”，进而明白“如果我们想做些什么，应该怎么利用它”。
学习去怀疑一切。
**** 理论性作品的分类
历史、哲学、科学
不同的学科老师讲课方式，使用的词语，讨论的方式，提出的问题，期望学生作出的答案都不相同。不同的学科有不同的教法，不同的课
程也有不同的学习方法。
*** 第七章 透视一本书
每一本书的封面之下都有一套自己的骨架，任何一本值得读的书，都会有一个整体性与组织架构。作为一个分析阅读的读者，你的责任就
是要找出这个骨架。
**** 架构与规划：叙述整本书的大意（规则二）
对于“整体内容”这件事，光是一个模糊的认识是不够的，你必须要确切清楚地了解才行。只有一个方法能知道你是否成功了：你必须能用
几句话，告诉你自己，或别人，这整本书在说的是什么。如果你要说的话太多，表示你还没有将整体的内容看清楚，而只是看到了多样的
内容；不要满足与“整体上的感觉”，自己却说不出口，这分明是根本不知道。
+ 一位作者，特别是好的作者，会经常想要帮助你整理出他书中的重点。书名和前言中通常都会体现整体内容的设计。
+ 不要把作者提供的重点摘要作为本书绝对又唯一的说明，作者也可能出错。找出架构是读者的责任。
总之，如果作者提供帮助，不要因为太骄傲而拒绝；但是也不要完全依赖作者在前言中所说的话。
**** 驾驭复杂的内容：为一本书拟大纲的技巧（规则三）
那是一栋大厦，拥有许多房间，每层楼也都有房间，有不同的尺寸与形状，不同的外观，不同的用途。这些房间是独立的，分离的。每个
房间都有自己的架构与装潢设计，但却不是完全独立与分离的。这些房间是用门、走廊、楼梯串联起来的，也就是建筑师所谓的“动线”（
traffic pattern）架构。因为这些架构是彼此连结的，因此每个部分在整体使用上都要贡献出自己的力量。否则，这栋房子便是不适于
居住的。
一本好书，就像移动好房子，每个部分都要很有秩序的排列起来，每个重要部分都要有一定的独立性。
可读性最高的作品是作者达到了建筑学上做完整的整体架构。最好的书都有最睿智的架构。虽然他们比一些差一点的书要复杂一些，但他
们的负责也是一种单纯，因为他们的各个部分都组织得更完善，也更统一。
***** 重要性
一份说明清楚的摘要会指出全书最重要的构成部分。你看不清楚这些构成部分，就没法理解全书。同样的，除非你能掌握全书各个部分
之间的组织架构，否则你也无法理解全书。
除非你遵循规则三，否则你没有办法有效运用规则二。你有可能有办法粗略地瞄一本书，就用一两个句子说出全书的重点摘要，而且还挺
得体。但是你却无法真的知道得体在哪里，你只是猜对了而已。
***** 规则要求
将一本书最重要的部分照秩序与关系，列举出来。
不只是将各个部分排列出来，而且要列出各个部分的纲要，就像是各个部分自成一个整体，各有各的整体性与复杂度。
规则二、规则三可以帮助我们区分好的作品和坏的作品。
规则二、规则三不但可以用来阅读一整本论说性的书，也可以用来阅读其中某个特别重要的部分。
***** 公式
1) 作者将全书分成五个部分，第一部分谈的是什么，第二部分的观点，......，第五部分又是另外一些事。
2) 第一个主要的部分又分成三个阶段，第一个阶段为X，第二个阶段为Y，第三个阶段为Z。
3) 在第一部分的第一阶段，作者有四个重点，第一个重点是A，第二个重点是B，第三个重点是C，第四个重点是D，等等。
即使依然读过很多次，现在使用这种方法来阅读，会看到许多以前你没看到的东西。
没必要一句书的章节来拟定大纲，依据自己的理解来拟定，才能读得明白。章节跟目录一样，具有指南的作用，但不要完全被动地依赖他
们。
***** 阅读与写作
写作与阅读是一体两面的事。写作用艺术的手法将骨架隐藏起来。对于一本书来说，血肉与骨架一样重要，血肉为纲要作进一步的解释，
为全书增添了必要的空间与深度。一个作品应该有整体感，清楚明白，前后连贯。
**** 发现作者的意图
一本书的作者在开始写作时，都是有一个问题或者一连串的问题，而这本书的内容就是一个答案，或许多答案。
你应该有办法说出整本书想要解答的问题是什么。否则就会对一本书的主题或重点很不清楚。
如果主要问题很复杂，又分成很多部分，你还要能说出次要问题是什么。还要明智地将这些问题整合出顺序来。哪一个主要的，哪个是次
要的？哪些问题要先回答，哪些是后来才要回答的？
遵守规则四，能让你和遵守前两条规则产生前后呼应的效果。
有助于说出作者想要表达的是什么，看清楚一本书的整体精神。
***** 简短公式
****** 理论下问题
某件事存在吗？是什么样的事？发生的原因是什么？或是在什么样的情况下存在？或为什么会有这件事的存在？这件事的目的是什么？造
成的影响是什么？特性及特征是什么？与其他类似事件，或不相同事件的关联是什么？这件事是如何进行的？
****** 实用性问题
有哪些结果可以选择？应该采用什么样的手段才能获得某种结果？要达到某个目的，应该采取哪些行动？以什么顺序？在这些条件下，什
么事是对的，或怎样才会更好，而不是更糟？在什么样的条件下，这样做会比那样做好一些？
**** 分析阅读的第一个阶段
规则一，你一定要知道自己在读的是哪一类的书，而且要越早知道越好。最好早在你开始阅读之前就先知道。
规则二，使用一个单一的句子，或最多几句话（一小段文字）来叙述这本书的内容。
规则三，将书中重要篇章列举出来，说明他们如何按照顺序组成一个整体的架构。
规则四，找出作者要问的问题。
***** 第一阶段规则目的
前四个规则有整体性，有一个目标：提供读者对一本书架构的认识。
有助于回答关于一本书的四个基本问题的第一个：整本书谈的是什么？
没必要为了要运用前四个规则，而将一本书读完，然后为了要运用其他的规则，再重新一遍又一遍读。真正实际的读者是一次完成所有的
阶段。
***** 分析阅读的第一阶段，找出一本书谈些什么的四个规则
1)依照书本的种类与主题作分类
2)用最简短的句子说出整本书在谈些什么
3)按照顺序与关系，列出全书的重要部分；将全书的纲要拟出来之后，再将各个部分的纲要也一一列出
4)找出作者在问的问题，或作者想要解决的问题
