#+TITLE:          cuda 编程基础
#+AUTHOR:         Kyle Three Stones
#+DATE:           <2018-12-30 Sun>
#+EMAIL:          kyleemail@163.com
#+OPTIONS:        H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t f:t tex:t
#+TAGS:           cuda, 深度学习
#+CATEGORIES:     深度学习


学习周斌老师的《NVIDIA CUDA 初级教程视频》笔记


** 重看 CPU

CPU 芯片中大量的晶体管用于 cache3 ，可以看到芯片中很大一部分面积都是 cache3 。主要由于 CPU 始终在大量的移动数据，将硬盘
中的数据移动到内存，将内存中的数据缓存到 cache ，将 cache 中的数据移动到寄存器，将某个寄存器移动到另一个寄存器，还有反向
的操作，将数据再写回硬盘，这些都是在大量的移动数据。CPU 主要是在为串行做优化，为了高速的数据移动，设计了内存管理单元、占
用很大芯片面积的 cache3 （或许是可以称 CPU 为吞吐机的原因），为了快速执行命令设计了各种分支预测、流水线、乱序执行等等。


*** 整体架构

1. CPU 可以分成 *数据通道* 和 *控制逻辑* 两个部分。
2. Fetch 取址 -> Decode 译码 -> Execute 执行 -> Memory 访存 -> Writeback 写回


*** Pipeline

流水线是指令级并行 ILP 。可以极大的减小时钟周期，但同时也可能存在延迟（啥？），会增大芯片面积，指令流前后有关系时，无法
很好的利用流水线。流水线的长度称为级，并不是越大越好，通常在 14-20 级，不公开，涉及到芯片设计的商业秘密。


*** Bypassing

不等待前一条指令的所有流水线执行完成，只需要得到前一条指令结果的某一个数据，直接通过一个特殊的通道传递。


*** Branches

1. 分支预测 Branch Prediction ，猜测下一条指令 ，基于过去分支记录，通常准确率大于 90%
1. 分支断定 Branch Predication ，不使用分支预测，同时执行所有的分支。可减小面积、减小错误预测


*** IPC

instructions per cycle ；超标量 superscalar ，增加流水线的宽度， N 条流水线。从而提高 IPC


*** 指令调度

1. Read-After-Write - RAW
1. Write-After-Read - WAR
1. Write-After-Write - WAW

寄存器重命名来改善


*** Out-of-Order OoO

乱序执行，重排指令，获得最大的吞吐率。可以重排缓冲区或发射队列/调度器


*** 存储器层次架构

寄存器 - L1 - L2 - L3 - 主存 - 硬盘

+ 硬件管理 :: L1 , L2, L3
+ 软件管理 :: 主存 , 硬盘

缓存： 将数据放在尽可能接近的位置；利用时间/空间的临近性。

1. 分区 Banking ，避免多端口
1. 一致性 coherency
1. 控制器 Memory Controller ，多个通道，增加带宽

编址方式

+ Shared Memory
+ Distributed Memory
+ Hybrid Distributed-shared Memory


*** CPU 内部并行性

1. 指令级并行 Instruction-Level extraction :: 超标量、乱序执行
1. 数据并行 Data-Level Parallelism :: 矢量计算，单指令多数据 Single Instruction Multiple Data (SIMD) ; 执行单元 ALU 很宽，
     寄存器很宽
1. 线程级并行 Thread-Level Parallelism :: 同步多线程 Simultaneous Multithreading SMT ，多核 Multicore


*** Multicore

+ 真多核 :: 除最后一级缓存外，不共享其他资源；
+ 假多核 :: 可能只是多个 ALU


*** 锁存

+ 多个线程读写同一款数据：加锁；
+ 谁的数据是正确的 ： 缓存一致性协议 Cohernce
+ 什么样的数据是正确的 Consistency ： 存储器同一性模型


*** Powerwall

由于能量墙的限制，导致摩尔定律无法保持。

新摩尔定律：多核、单核性能并不会大幅度提升，频率也基本不会有大的提升；

处理器的存储器带宽无法满足处理能力的提升。


*** Flynn 矩阵

| SISD | SIMD |
| MISD | NIND |


*** 名词不解释

+ Task 任务
+ Parallel Task 并行任务
+ Serial Execution 串行执行
+ Parallel Execution
+ Shared Memory 共享存储
+ Distributed Memory 分布式存储
+ Communication 通信
+ Synchronization 同步 --> 破坏了独立性、并行性
+ Granularity 粒度 --> 任务划分的粒度
+ Observed Speedup --> 加速比
+ Parallel Overhead 并行开销 --> 通信、同步
+ Scalability 可扩展性 --> GPU 从 4 核到 400 核时，性能上的提升


*** 并行编程模型

+ 共享存储模型 shared memory model
+ 线程模型 threads model
+ 消息传递模型 message passing model
+ 数据并行模型 Data Parallel Model --> 对数据切分

OpenMP , MPI , SPMD , MPMD


*** Amdahl's Law

程序可能的加速比取决于可以被并行化的部分： speedup = 1/(1-p)

设计并行处理程序和系统


** GPU 设计思路

1. 去掉复杂的分支预测、乱序执行、内存管理等单元
1. 设计加入多个核（多个 SM）
1. 在一个核内增加 ALU 的宽度；即一个核内有多个 ALU ，ALU 被分成多个组，每个组内的 ALU 共享管理调度单元（指令流）
1. 提供较大的上下文存储空间（pool of context storage），使得大量独立片元切换来掩藏延迟。每个 SM 上可以驻扎远多于 SP 个数
   的线程

最终设计结果：一个 GPU 有多个 Streaming Multi-processor [SM] ，每个 SM 内有多个 Streaming Processor [SP] ，也就是 cuda
core ，是最小的计算单元 ALU 。每个 SM 内的 cuda core 被分成多个组，有多个调用单元用于调度，一个调度单元同一时间可以调度
一个组，使得一个组内所有线程执行相同的指令，但读取不同的数据。同时一个 SM 内有一定数量的寄存器、共享存储空间、上下文存储
空间，动态分配给需要的单元。

具体编程时，并不需要关心具体的硬件结构， cuda 将线程设计了三级逻辑抽象： grid - block - thread 。并不与硬件结构一一对应。

1. 一个 Grid 内，每个 Block 的线程数是一样的
1. Block 内每个线程可以 synchronize 同步；
1. Block 内每个线程都可以访问 shared memory ；
1. 每个 Block 内最多的线程数有一定的限制（不同的芯片会不一样）；
1. *一个 Block 内的所有线程必须位于同一个 SM 中* ；
1. Block 之间彼此相互独立执行，以任意顺序、任意调度；在运行期确定在哪个 SM 上调度，可扩展

GPU 适用于密集计算，高度并行的计算；其片上晶体管主要用于执行计算，而不是缓存数据或控制指令流。

GPU 带宽是非常宝贵的资源，应该尽量减少带宽请求次数，重复数据尽量只取一次。让 GPU 多做运算。GPU 显存很大，相对内存来说，
带宽也很大，但在片外（不再 GPU 芯片内，在显卡的板子上），但芯片内部局部存储较小，缓存较小。

#+BEGIN_EXAMPLE
# CPU GPU 协同方式；好难对齐呀！！！
主存              显存
DRAM             GDRAM
 |                 |
CPU               GPU
 |                 |
I/O  <--------->  I/O
         PCIE
#+END_EXAMPLE

SSE 显示向量运算指令；但 SIMD 处理并不总是需要显示 SIMD 指令，NVIDIA GPU 标量指令，但硬件进行矢量化，是 SIMT （单指令多
任务）

GPU 架构决定，编写 GPU 代码的时候需要注意

1. 尽量少用递归，至少不鼓励使用递归，尤其是很深层次的递归
1. 不要使用静态变量
1. 少用 malloc 函数，因为成千上万个线程都执行 malloc ，可能导致显存很快用尽，同时也会影响性能（猜测）
1. 小心通过指针实现函数调用（注意区分设备侧和主机侧地址）


** GPU 内存模型

+ 寄存器 :: 片上，快速，可读写；线程专用。每个 SM 上有一定数量的寄存器，如 G80 ，每个 SM 有 8K 个寄存器
+ Local Memory :: 在片外的 Global Memory 中，每个线程私有。可存储稍微大一些的数据，一般用于存储自动变量数组，通过常量索
                  引访问；新的 GPU 有 cache 
+ Shared Memory :: 片上，全速随机访问，可读写； block 内共享。和 cache 在同一个层次，可理解为用户可编程的 cache 。每个
                   SM 内有固定大小的共享存储器，如 G80 中，一个 SM 有 16 KB shared memory ；需要注意 bank conflict
+ Global Memory :: 片外，长延时（100 个时钟周期），可读写，随机访问性能差；带宽较大 300GB/s ，有 cache ；Host 可读写
+ Constant Memory :: 在 Global 中特定位置，即固定的地址，短延迟、高带宽、所有线程只读，容量较小，cache ；Host 可读写

| 存储器   | 编程声明                                     | 作用域 | 生命期      |
|----------+----------------------------------------------+--------+-------------|
| register | 编译器管理，必须是单独的自动变量而不能是数组 | thread | kernel      |
| local    | 编译器管理，自动变量数组                     | thread | kernel      |
| shared   | __ shared__ int sharedVar                    | block  | kernel      |
| global   | __ device__ int globalVar                    | grid   | application |
| constant | __ constant__ int constantVar                | grid   | application |


** 线程调度

cuda 通过分级管理线程 Grid - Block - warp - Thread 。 逻辑 Block 可以想象对应硬件的 SM 。

warp 是 Block 内线程编号连续的 32 个线程， *是线程调度的最小单元* 。warp 运行在一个 SM 中，threadIdx 值连续，硬件设计上
保证 warp 内的每个线程同步。

特征：

1. 在硬件上，warp 的调度是 0 开销的（所有 warp 的上下文已经存储在硬件中）
1. 同一时间，一个 SM 上只有一个 warp 在执行（不是一个 SM 上有多个调度器吗？多个调度器应该是可以同时执行多个 warp 的呀？
   TODO）
1. warp 内所有线程始终执行相同的指令

+ divergent warp :: 由于没有为每个线程设计一个调度器（会占用额外的芯片面积），一个 warp 共享一个调度器，所以所有的线程必
                    须执行相同的命令。如果有条件分支，那么 warp 内的所有线程都会执行所有的分支，只是线程在不需要的分支时
                    候不操作任何寄存器。warp 内分支发散 GPU 做了一些优化，不太不要重点关注。但需要考虑好的算法数据分割，
                    使得warp 能尽早完工，释放资源，从而更好的利用资源，如并行规约 Parallel Reduction 的一个简单情况，求
                    一个数组的和，算法每次执行两个数的相加，如果始终让相邻的两个数相加，那么 warp 将无法很好的被利用，修
                    改成让两个相差数组长度一半索引的两个数相加，之后的 warp 就可以较早的被释放。

问： 每个 warp 有 32 个线程，但每个 SM 中只有 8 个 SP ，这时候如何调度呢？

答： 将 warp 分成四组，第一个时钟周期前 8 个线程执行一条命令，第二个时钟周期，随后的 8 个线程执行相同的命令，直到第四个
时钟周期，所有 32 个线程都执行完某一条命令，然后再执行下一条命令。即一条指令分成四次调度才能执行完成。当然这是很老的 GPU
才有的现象，现代 GPU 一个 SM 内 SP 的个数很多，不再需要分多次才能执行完一个 warp 。不过这种逻辑思想是一样的。

| 架构     | SM 中 SP 的数量 |
|----------+-----------------|
| 开普勒   |             192 |
| mashival |             128 |
| Fermi    |              32 |

问： 假设一个 kernel 包含 1 次 global memory 的读操作，需要 200 个 cycles ，和 4 次独立的 multiples/add 操作，需要多少
warp 才能隐藏内存延迟？

答： 4 次乘/加操作，每次乘/加需要 4 个 cycles ，共需要 16 个 cycles ； 200/16 并向上取整得到 13 个 warp 。 TODO！@#￥%


线程同步可能导致 *死锁* ，需要注意逻辑正确性

#+BEGIN_SRC c
# 下面代码将导致死锁
if (condition) {
    ....
    __syncthread();
}
else {
    ....
    __syncthread();
}
#+END_SRC


** CUDA 开发工具

1. nvcc 编译器
1. cuda-gdb 调试器，和 gdb 一样，额外增加了 cuda 相关命令，可通过 help cuda 查看
1. nvprof 性能分析工具，注意后面接的程序要加相对路径，否则会找不到进程

Developer Zone 查看资料；两个主要的手册 <CUDA C programming Guide> 和 <CUDA C Best Practices Guide>

cuda 和 OpenCL 是同一级别的。


** cuda 算法框架

1. 在设备侧分配空间和初始化
1. 并行计算，kernel 函数
1. I/O 回主机，释放内存

*cuda 算法最主要的性能问题是访存* ，GPU 计算能力很强，应该努力 exploit exploied 其计算性能。

矩阵乘法，使用 CPU 代码需要三层循环，外面两次遍历结果矩阵的行和列，第三个循环用于一行和一列的乘和累加；而 cuda 代码已经
不需要外面的双层循环了，因为通过不同的线程索引，由 GPU 的并行线程处理了。同时不需要锁或者同步，因为各个计算单元相互独立，
互不依赖。

只有 block 内的同步，没有全局同步。block 内同步要求线程执行时间尽量接近，否则会浪费计算资源；而全局的同步需要很复杂的硬
件结构，会有很大的开销，所以并没有设计。


** GPU 向量数据类型 - 函数库

| char[1-4]  | uchar[1-4] |
| int[1-4]   | uint[1-4]  |
| long[1-4]  |            |
| float[1-4] |            |
| double1    | double2    |

#+BEGIN_SRC c
int4 i4 = make_int4(1,2,3,4);

int x = i4.x;
int y = i4.y;
int z = i4.z;
int w = i4.w;
#+END_SRC

cuda 提供常见的函数库，如正余弦、指数等，同时提供低精度的版本，函数名前加两个下划线，这些函数执行更快，但精度较低


** cuda 优化

有效的数据并行算法 + 针对 GPU 架构特性的优化 = 最优性能


*** 存储优化

**** 较少 CPU 和 GPU 侧数据的传输

1. Host - device 数据数据传输 PCIe 带宽远低于设备访问 global memory
1. 减少传输：中间数据直接在 GPU 分配、操作、释放；如果没有减少数据传输，将 CPU 代码移植到 GPU 可能无法提升性能；GPU 有足
   够的计算单元，不怕计算，怕数据传输
1. 组团传输：大块传输好于小块传输；
1. 内存传输与计算时间重叠：双缓存


**** 访存合并

*coalescing 合并是最重要的性能影响因子* 。Global memory 延迟通常在数百个 cycles 。

给定一个矩阵以行优先的方式存储于 global memory ，一个 warp 内相邻的 thread 分别读取相邻地址的数据（第 k 个线程读取第 k
段数据，如果有一些交叉或者错位也没有太大关系），就是合适的访存模式。忌讳随机凌乱的访问和一个线程访问很长的地址空间，会造
成多次数据读取，有很大带宽浪费。

设计程序时，优先考虑怎么样设计一个规则的访存访问模式。如果不规则，可以先读入 shared memory 中，然后在 shared memory 中不
规则访问，或者重排；


**** shared memory
*shared memory 的设计很大程度上就是由于应对不规则的存储器访问* 。shared memory 比 global memory 快上百倍，可以缓存数据来
减少对 global memory 访问次数，线程协作，以及避免不满足合并条件的访存。

shared memory 被分成许多 banks 区块，连续地址被分配到连续的 Banks 上，一个 bank 上存储了多个地址的数据（余数相同的地址存
储在同一个 bank 上）。每个 bank 每个周期可以响应一个地址请求，多个线程访问同一个地址请求有相应的广播机制，没有问题。但对
同一个 bank 进行多个并发访存（不同地址）将导致 *bank 冲突* ，冲突的访存必须串行执行。[不明白一个 bank 存储的是一个 bit
还是一个 byte ，不过好像没有什么太大关系，总之是一个 bank 内存储了多个不同地址的数据，同一个时钟周期只能响应一个地址请求]

如果没有 bank 冲突， shared memory 和 registers 访问速度是同量级的。同时有几个线程在访问同一个同一个 bank 的不同地址，就
是几路 bank 冲突 8 way bank conflict 。几路 bank 冲突就会导致性能下降几倍。 *避免 bank 冲突的方法* ： 数组宽度加一
tile[TILE_DIM][TILE_DIM] ，来填充 shared  memory 数组。这样将使得读取和写入都不存在 bank 冲突。

矩阵转置需要同时访问行和列，这就导致访存不合并。


**** Texture memory

无法合并访存，同时又有多种寻址方式，以及小的数据区块读取。如坐标越界寻址（warp/clamp） 。

只需要将 global memory 绑定到 texture memory 就可以正常使用。


**** Occupancy

一个 SM 里面激活 warp/最多可容纳 warp 数目 ； 代表了 GPU 的繁忙程度。

SM 资源动态划分有多个约束，哪一个约束都得满足，那个约束先达到上限，其他约束将失效，影响 SM 同时启动线程的数量；可能导致
performance cliff


**** Grid - Block 大小

***** Grid size 试探法

1. block 个数 > SM 的个数，保证每个 SM 至少有一个 work-group
1. block 个数 / SM 个数 > 2 ，多个 block 可以在 SM 上并发执行，如果一个 block 在等待，启动另一个 block
1. block 个数 / SM 个数 > 100 ，对未来设备有良好的伸缩性


***** Block size

1. block 大小最好是 32(warp 的大小) 的倍数 
1. 尽量多的 warp 进行延迟掩藏
1. block 通常是 128 , 256 可以进行尝试


**** Latency Hiding

延迟掩藏：指令按顺序执行，一个线程的任一操作数没有准备好将阻塞等待；延迟可以通过足够多的线程切换来隐藏。

延迟掩藏和 warp 个数以及占用率的计算没有看懂。


**** Data Prefetching

数据预读取。让数据读取和计算并行


**** 指令优化

较后考虑的事情

#+BEGIN_SRC c
num / 2^n --> num >> n
num / 2^n --> num &(2^n-1)
#+END_SRC


**** Unroll loop

循环展开，去掉不必要的判断语句，增加代码速度。但不利于扩展

#+BEGIN_SRC c

#pragma unrool BLOCK_SIZE
for (i = 0; i < BLOCK_SIZE; ++i) {
...
}
#+END_SRC

**** 总结

1. 有效利用并行性
1. 尽可能合并内存访问
1. 利用 shared memory
1. 利用 Texture / constant memory
1. 减少 bank 冲突



