#+TITLE: 基础心理学
#+AUTHOR: 三石
#+DATE: <2017-07-03 Mon>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 

* 心理暗示
一种主观意识上被肯定的假设，不一定有根据，但是由于主观上已经肯定了他的存在，所以在心理上便竭力倾向于这项内容。

* 心理战术
先上她失望，然后再给她希望，那样她就会深信不疑。

* 偷东西
绿林人抛砖引玉的方法，《三侠五义》

* 胜败
有时候暂时的失利比暂时的胜利要好很多。

谁都不傻，但谁都有傻的时候。

木秀于林，风比摧之；堆出于岸，流必湍之；行高于人，人必非之。

* 自信 self-confidence
The ability or the belief to believe in yourself, to accomplish any task, no matter the odds, no matter the difficulty,
no matter the adversity.
The belief that you can accomplish it.
Thoughts influence actions.
Self-confidence people interpret feedback the way they choose to.
No one will believe in you unless you do.
方法：
+ Repetition. Repetition. Repetition.
+ Write a letter to myself, it was my own brag sheet. My own letter about the thing I was proud of.
+ Stop the negative self-talk.

* 生活
Life is short, don't live the same day twice.

* 独处时的人性
真实的人性只存在一个人独处的时候。

* 付出越多只会让你爱她越多
对一个人付出越多，只会让你更爱她，而不会另他更爱你 -- 心理学基本法则;
这个道理大多数人一辈子都搞不明白；
心理学上，你对一个人的每次付出，都是一笔情感投资，投资越多，你对投资对象的感情就
越深。
母亲由于天天照顾孩子，而变得越来越离不开孩子，即使是养子也一样：
亲情的基石不是血缘，而是付出。
还有父母最疼的那个孩子，与最孝顺父母的永远不是同一个。
太多陷入爱情的人，最怕付出的爱收不回，于是心里的安全感会驱使他们继续疯狂的投入感情。
但是这样只会让自己更加爱对方，而不是反之。于是有太多女人为渣男付出一切后被抛弃的故事。
当我们已看清一个人狼心狗肺，不值得付出时，就应及时止损，停止一切投入，千万别因为
不甘心而继续，那样只会让你像个赌徒一般越陷越深。
** 对应到人际关系
别人对你的每次付出，都是一次情感投资，随着投资增多，他对你的亲近感才会加深。
而真正情商高的人都懂得如何巧妙的引导别人对自己进行感情投资，以此增进与亲朋好友
甚至陌生人的感情。
推销员：每次敲开一家陌生人的门，他都不会立刻提推销之事，而是向主人客气的要一杯水。
帮了你一个小忙后，人往往倾向于再帮你一个大忙。
华盛顿曾经想要一个固执的议员帮忙，也是先打听到他有一本珍藏的书籍，于是先借阅了
几天，等到还书时，议员和华盛顿已经亲近不少。
触龙也是先让赵太后帮忙给自己儿子安排一个职位才成功说服赵太后让长安君去做人质。
*** 如果你想结交一个人，就先找他帮个忙。
我从小就是一个不愿意麻烦别人的人，长辈们一直叮嘱我不要给别人添麻烦；
这只让自己成了一个行单影只的好人。要从一个好人，变成一个聪明人。

* 随机应变能力
老友记第五季第六集中 00:07:45--00:08:56 中 Rechel 对Danny 的不同反应的三次回应。
