#+TITLE: 常见心理学效应
#+AUTHOR: 三石
#+DATE: <2017-06-08 Thu>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 

* 羊群效应
“羊群效应”也叫“从众效应”：是个人的观念或行为由于真实的或想象的群体的影响或压力，而向与多数人相一致的方向变化的现象。
无论意识到与否，群体观点的影响足以动摇任何抱怀疑态度的人。群体力量很明显使理性判断失去作用。

羊群是一种很散乱的组织，平时在一起也是盲目地左冲右撞，但一旦有一只头羊动起来，其他的羊也会不假思索地一哄而上，全然不顾前
面可能有狼或者不远处有更好的草。因此，“羊群效应”就是比喻人都有一种从众心理，从众心理很容易导致盲从，而盲从往往会陷入骗局
或遭到失败。

羊群效应的出现一般在一个竞争非常激烈的行业上，而且这个行业上有一个领先者（领头羊）占据了主要的注意力，那么整个羊群就会不
断模仿这个领头羊的一举一动，领头羊到哪里去“吃草”，其它的羊也去哪里“淘金”。

一则幽默
一位石油大亨到天堂去参加会议，一进会议室发现已经座无虚席，没有地方落座，于是他灵机一动，喊了一声：“地狱里发现石油了！”这
一喊不要紧，天堂里的石油大亨们纷纷向地狱跑去，很快，天堂里就只剩下那位后来的了。这时，这位大亨心想，大家都跑了过去，莫非
地狱里真的发现石油了？于是，他也急匆匆地向地狱跑去。
松毛虫实验
法国科学家让约翰·法伯曾经做过一个松毛虫实验。他把若干松毛虫放在一只花盆的边缘，使其首尾相接成一圈，在花盆的不远处，又撒
了一些松毛虫喜欢吃的松叶，松毛虫开始一个跟一个绕着花盆一圈又一圈地走。这一走就是七天七夜，饥饿劳累的松毛虫尽数死去。而可
悲的是，只要其中任何一只稍微改变路线就能吃到嘴边的松叶。


* 镜子效应

镜子效应来源与现实的生活，主要用于人际交往。当你照镜子时，镜子里的你会随着你的喜怒哀乐而变化。这是最狭义的镜子效应！同样
的，在人际交往中，你对别人好，别人也会对你好。相反你对别人不好，别人也对你不好！这就是镜子效应的真谛！ 在现实中的应用。
当你和你不喜欢的人相处时，或许他也不怎么喜欢你，但是只要你试着慢慢的喜欢他，逐渐的他也会开始喜欢和你相处！人都是相互的！


* 多看效应
对越熟悉的东西越喜欢的现象，心理学上称为“多看效应”。多看效应不仅仅是在心理学实验中才出现，在生活中，我们也常常能发现这种
现象。
有些人善于制造双方接触的机会，从而提高彼此间的熟悉度，互相产生更强的吸引力。在我们新认识的人中，有时会有相貌不佳的人，最
初，我们可能会觉得这个人难看，可是在多次见到此人之后，逐渐就不觉得他难看了，有时甚至会觉得他在某些方面很有魅力。
实验
20世纪60年代，心理学家查荣茨做过这样一个实验：他向参加实验的人出示一些人的照片，让他们观看。有些照片出现了二十几次，有的
出现十几次，而有的则只出现了一两次。之后，请看照片的人评价他们对照片的喜爱程度。结果发现，参加实验的人看到某张照片的次数
越多，就越喜欢这张照片。他们更喜欢那些看过二十几次的熟悉照片，而不是只看过几次的新鲜照片。也就是说，看的次数增加了喜欢的
程度。
另一个实验：在一所大学的女生宿舍楼里，心理学家随机找了几个寝室，发给她们不同口味的饮料，然后要求这几个寝室的女生，可以以
品尝饮料为理由，在这些寝室间互相走动，但见面时不得交谈。一段时间后，心理学家评估她们之间的熟悉和喜欢的程度，结果发现：见
面的次数越多，相互喜欢的程度越大；而见面的次数越少或根本没有，相互喜欢的程度就较低。
作用
可见，若想增强人际吸引，就要留心提高自己在别人面前的熟悉度，这样可以增加别人喜欢你的程度。因此，一个自我封闭的人，或是一
个面对他人就逃避和退缩的人，由于不易让人亲近而令人费解，也就是不太让人喜欢了。想想看，你周围有没有常在你面前“露脸”的人。
如果想给别人留下不错的印象，常出现在他面前就是一个简单有效的好方法。
所以，作为大学生，如果你想改善自己的人缘，不妨多在寝室间走动一下，即使只是露个脸，借瓶开水，换本书。在这些细节的来来往往
中，就无形中提高了自己的人际吸引力，也获得了你所期待的群众基础。作为职场人士，埋头苦干也并非明智之举。自我封闭，不与人交
往，遇事逃避退缩，只会让你的职业发展之路止步不前。
当然，“多看效应”并非万能钥匙。它发挥作用的前提是，首因效应要好，即给人的第一印象不是很差，如果第一印象就很差，那么见面越
多就越惹人讨厌，“多看”反而让人“多厌”，那就得不偿失了。所以，一切的前提，还是认清自己，理顺了，再拿给别人看。


* 标签效应
当一个人被一种词语名称贴上标签时，他就会作出自我印象管理，使自己的行为与所贴的标签内容相一致。这种现象是由于贴上标签后面
引起的，故称为“标签效应”。
心理学认为，之所以会出现“标签效应”，主要是因为“标签”具有定性导向的作用，无论是“好”是“坏”，它对一个人的“个性意识的自我认
同”都有强烈的影响作用。给一个人“贴标签”的结果，往往是使其向“标签”所喻示的方向发展。


* 鸟笼效应
鸟笼效应：假如一个人买了一只空鸟笼放在家里，那么一段时间后，他一般会为了用这只笼子再买一只鸟回来养而不会把笼子丢掉，也就
是这个人反而被笼子给异化掉了，成为笼子的俘虏。
鸟笼效应是一个著名的心理现象，又称“鸟笼逻辑”，是人类难以摆脱的十大心理之一 ，其发现者是近代杰出的心理学家詹姆斯。“鸟
笼效应”是一个很有意思的规律，人们会在偶然获得一件原本不需要的物品的基础上，自觉不自觉的继续添加更多自己不需要的东西。


* 禁果效应
禁果效应也叫做“亚当与夏娃效应”，越是禁止的东西，人们越要得到手。越希望掩盖某个信息不让别人知道，却越勾起别人的好奇心和探
求欲，反而促使别人试图利用一切渠道来获取被掩盖的信息 。这种由于单方面的禁止和掩饰而造成的逆反现象，即心理学上的“禁果
效应” 。这与人们的好奇心与逆反心理有关。有一句谚语：“禁果格外甜”，就是这个道理。


* 刺猬效应
刺猬效应（Hedgehog Effect），是指刺猬在天冷时彼此靠拢取暖，但保持一定距离，以免互相刺伤的现象。这个比喻来自叔本华的哲学
著作，它强调的是人际交往中的“心理距离效应”。刺猬效应的理论可应用于多种领域。在管理实践中，就是领导者如要搞好工作，应该与
下属保持“亲密有间”的关系，即为一种不远不近的恰当合作关系。在教育学中，教育者与受教育者日常相处只有保持适当的距离，才能取
得良好的教育效果。


* 淬火效应
淬火效应，原意指金属工件加热到一定温度后，浸入冷却剂（油、水等）中，经过冷却处理，工件的性能更好、更稳定。心理学把这定义
为“淬火效应”。教育上也会有类似的现象，被称之为“冷处理”。
在心理学与教育学中衍生出的含义为长期受表扬头脑有些发热的学生，不妨设置一点小小的障碍，施以“挫折教育”，几经锻炼，其心理会
更趋成熟，心理承受能力会更强；对于麻烦事或者已经激化的矛盾，不妨采用“冷处理”，放一段时间，思考会更周全，办法会更稳妥。


* 负重效应
负重效应起源于一个航海故事。
有一位经验丰富的老船长，当他的货轮卸货后在浩淼的大海上返航时，突然遭遇到了狂风巨浪。水手们惊慌失措，急得团团转。老船长果
断地命令水手们立刻打开所有的货舱，往里面灌水。“怎么能够往船舱里灌水呢？这样只会增加船的重量，使船迅速往下沉，这是自寻死
路啊！”不少年轻的水手不解地问道。但看着船长严厉的脸色和毫无商量的神情，水手们只好半信半疑地照做了。随着货舱里的水位越升
越高，随着船一寸一寸地下沉，依旧猛烈的狂风巨浪对船的威胁却一点一点地减少，货轮渐渐平稳了。船长望着松了一口气的水手们说：
“一只空木桶，是很容易被风打翻的，如果装满水负重了，风是吹不倒的。同样道理，船在负重时是最安全的，空船时则是最危险的。”于
是，人们将这种现象称之为“负重效应”。
科学家计算过，倘若地球上的鱼一年之内产的鱼仔都能成活，都能顺利长成成鱼，可以把地球上江湖河海都塞满，然而事实却不是这样，
从鱼仔到成鱼，要经历千百次的自然和自身的淘汰。最优秀的和最适应的才能留了下来。自然界要维持其自身的平衡功能，都是在各种压
力下完成的，否则生物就会逐步退化。孩子的成长也应该如此，当有的爱对孩子来讲是不愿承受的负担时，就可以要求在孩子不同的年龄
里承担不同的责任，适当、适时的压力也是孩子成长的强大动力。


* 出丑效应
出丑效应又叫仰巴脚效应，犯错误效应(PRATFALLEFFECT)：是指才能平庸者固然不会受人倾慕，而全然无缺点的人，也未必讨人喜欢。最
讨人喜欢的人物是精明而带有小缺点的人，此种现象亦称为仰巴脚效应。
出丑效应：意指精明的人无意中犯点小错误，不仅是瑕不掩瑜，反而更使人觉得他具有和别人一样会犯错的缺点，反而成为其优点，让人
更加喜爱他。仰巴脚就是不小心跌了一跤，有时可能要跌个脊背着地，四脚朝天，所以，又叫“出丑效应”。生活中有不少比较完美精明的
人。其实，这种完美往往是外在的表演，这样就未必讨人喜欢了。因为一般人与完美无缺的人交往时，总难免因己不如人而感到惴惴不安。
最讨人喜欢的是那些精明而小有缺点的人，比如，学生眼中的老师，老师眼中的领导，老百姓眼中的大官等。这些貌似完美无缺的人在不
经意中犯个小错误，不仅是瑕不掩瑜，反而让人觉得他和大家一样有缺点，就因为他显露出平凡的一面而使周围的人都感到了安全。
注：pratfall一字是英文中的俚语，意同北京土话“仰巴脚儿”。指不小心摔个四脚朝天的姿势，准此而论，此效应亦可称为“仰巴脚效应”。

就是对于那些取得过突出成就的人来说，一些微小的失误比如打翻咖啡杯这样的细节，不仅不会影响人们对他的好感，相反，还会让人们
从心理感觉到他很真诚，值得信任。而如果一个人表现得完美无缺，我们从外面看不到他的任何缺点，反而会让人觉得不够真实，恰恰会
降低他在别人心目中的信任度，因为一个人不可能是没有任何缺点的，尽管别人不知道，他心里对自己的缺点也可能是心知肚明的。


* 踢猫效应
踢猫效应是指对弱于自己或者等级低于自己的对象发泄不满情绪，而产生的连锁反应。
“踢猫效应”，描绘的是一种典型的坏情绪的传染。人的不满情绪和糟糕心情，一般会沿着等级和强弱组成的社会关系链条依次传递。由金
字塔尖一直扩散到最底层，无处发泄的最弱小的那一个元素，则成为最终的受害者。其实，这是一种心理疾病的传染。
一般而言，人的情绪会受到环境以及一些偶然因素的影响，当一个人的情绪变坏时，潜意识会驱使他选择下属或无法还击的弱者发泄。受
到上司或者强者情绪攻击的人又会去寻找自己的出气筒。这样就会形成一条清晰的愤怒传递链条，最终的承受者，即“猫”，是最弱小的群
体，也是受气最多的群体，因为也许会有多个渠道的怒气传递到他这里来。
现代社会中，工作与生活的压力越来越大，竞争越来越激烈。这种紧张很容易导致人们情绪的不稳定，一点不如意就会使自己烦恼、愤怒
起来，如果不能及时调整这种消极因素带给自己的负面影响，就会身不由己地加入到“踢猫”的队伍当中——被别人“踢”和去“踢”别人。


* 鲶鱼效应

鲶鱼效应：鲶鱼在搅动小鱼生存环境的同时，也激活了小鱼的求生能力。鲶鱼效应是采取一种手段或措施，刺激一些企业活跃起来
投入到市场中积极参与竞争，从而激活市场中的同行业企业。其实质是一种负激励，是激活员工队伍之奥秘。
挪威人喜欢吃沙丁鱼，尤其是活鱼。市场上活鱼的价格要比死鱼高许多。所以渔民总是想方设法的让沙丁鱼活着回到渔港。可是虽然经过
种种努力，绝大部分沙丁鱼还是在中途因窒息而死亡。但却有一条渔船总能让大部分沙丁鱼活着回到渔港。船长严格保守着秘密。直到船
长去世，谜底才揭开。原来是船长在装满沙丁鱼的鱼槽里放进了一条以鱼为主要食物的鲶鱼。鲶鱼进入鱼槽后，由于环境陌生，便四处游
动。沙丁鱼见了鲶鱼十分紧张，左冲右突，四处躲避，加速游动。这样沙丁鱼缺氧的问题就迎刃而解了，沙丁鱼也就不会死了。这样一来，
一条条沙丁鱼活蹦乱跳地回到了渔港。这就是著名的“鲶鱼效应”。
（有学者文章指出，“鲶鱼效应”的主体内容存在致命瑕疵：鲶鱼属于生活在江河湖等淡水水体中的鱼类，而沙丁鱼则属于海洋咸水鱼类，
运输沙丁鱼需要使用海水，将鲶鱼放入海水将导致鲶鱼死亡，根本不可能出现两种物种共生并相互影响的情况。目前关于鲶鱼效应的描述
都是中文，并没有确切的外文文献引用可以说明其出处是国外，且没有数据表明其在实践中的有效性，请读者斟酌采纳。）
启示
鲶鱼效应对于“渔夫”来说，在于激励手段的应用。渔夫采用鲶鱼来作为激励手段，促使沙丁鱼不断游动，以保证沙丁鱼活着，以此来获得
最大利益。在企业管理中，管理者要实现管理的目标，同样需要引入鲶鱼型人才，以此来改变企业相对一潭死水的状况。


* 费斯汀格法则

生活中的 10% 是由发生在你身上的事情组成，而另外的 90% 则是由你对所发生的事情如何反应所决定。
