#+TITLE: 情商
#+AUTHOR: 三石
#+DATE: <2017-11-18 Sat>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 


** 真正的情商高手，少不了对情绪的洞察

心里学家Kang和Shaver的研究发现，一个情绪管理能力越强，TA的情绪复杂度也就越高，情绪回路也越多。而情绪复杂度高的关键就在于，
他们习惯分析他人的情绪，这使得他们有了更多的机会，从中学习情绪的多种回路表达。
很多研究表明，人识别面部情绪表达是由特定的神经通路实现的，当这些结构损伤时，人识别情绪的能力就会发生障碍，这样的人往往在
人际交往中四处碰壁。因为如果一个人失去了，从别人身上学习情绪的机会，那他就只能依赖自己的情绪经验，然而每个人的体验都是有
限的。甚至大多时候，由于当局者迷，我们自身也缺少识别情绪的能力。这会让我们在情商提高这件事上，陷入瓶颈。通俗地说，读千卷
书，行万里路，都不如阅人无数。
情绪复杂度高的人，对他人的情绪产生的多样化原因，能有更加深度的认识，这使得他们能有更好的方法，更多的语言来解决别人的情感
冲突，引得他人的理解。情绪的识别面小了，我们太容易钻牛角尖，容易把人活活逼死。所以太史公司马迁说过：世间本无事，一切在人
心。


*** 例子
**** 朋友
***** 案例

当我因为命运的一些戏剧变化，突然间生活状态远高于过去时，即便我最好的朋友，也难以对我发自内心的祝贺。哪怕我有下乡支教这种
比较硬派的高尚美德，嫉妒情绪也会妨碍她们由衷替我感到高兴。老朋友们之所以不高兴，是因为她们突然发现，似乎我的地位可能高过
了她们时，她们认为这是一种对她们尊严的冒犯。


***** 回答

当别人嘲讽时，我回答：“别说，我恐怕混不到约炮的那天，就已经被人骂死了吧。我这种满身晦气的网红，哪有女生看得上。要想真正
赚到钱，怕是要我们一起才行哦！”
回答要点，在急着炫耀自己成就前，先用一些事实让对方觉得‘我并没有比你强’，从而消除焦虑。之后再提醒对方，对于我的改变，他们
可以有其他的角度去思考。所以，没必要急着批评朋友们出现的嫉妒情绪，这不过是一种‘我是否安全’的危险觉知。你需要充分察觉到对
方的情绪，引导他们走出负面的揣测。
亚当斯密把这种处境比喻为‘好运者的悲剧’，他认为这样的人，会走上放弃人际间感情链接，拼命努力的道路，然后有一天，会因为事业
的受挫，身边缺乏社会支持，精神备受打击，从而一蹶不振。


***** 总结

我们之所以在这样的情景里，所有的解释都感到苍白无力，就是因为对方的情绪系统其实被堵住了，你需要先引导他把情绪管道里的某些
东西释放出来，他才可能接收到你的某些积极能量。你应该顺从他们的意思帮助他们缓解焦虑，因为焦虑往往会让人，只注意到眼前的威
胁，即我似乎比他们地位高，他们很难从更大的角度去思考一些问题，比如是否可以学习一点我的经验，从其他途径为自己积累资本。
所谓孤独不是身边没人，就是你面对的那个人，他的情绪和你的情绪不再同一个频率。当解决了焦虑这个情绪时，对方的情绪同类才会畅
通，阳光才能照进别人的心里。


**** 女老师
***** 案例

有位大学女老师吐槽：“我最近压力太大了，学校为了评文明单位，我每天晚上都工作到十一点，我有个朋友因为忙，孩子都流产了，真
是不想干下去了。但评上后，今年会多发一个月工资。”
这个时候要学会识别她的情绪，她此刻的情绪，比起‘焦虑’更像‘愤怒’，一种对领导安排工作不合理的愤怒。但内心确实又没法完全否定
这件事的意义，这使她矛盾。接着，你要学会和她的情绪对话，疏导它的情绪。


***** 回答

“可能你们领导觉得，一个单位材料越多就越文明，就算他们对待员工的方式，不是很文明”


***** 总结

这里，疏导的关键就在于，你要用一种高度总结，逻辑严密的句子，把对方想说又不知道说的东西表达出来。他的内心仿佛有一种堵着的
东西，被你一说，瞬间就通畅了。网络上很多意见领袖，就是靠这样的方式吸粉，可以说，这是一种很高级的提供情感价值的方式，叫做
帮你说出，你想说的话。


**** 小乌龟
***** 案例

有姑娘和我倾诉：“我曾经养过一只小乌龟，后来我去旅游，就把它托付给我爹照顾，谁知道回来的时候，我的小乌龟就被我爹养死了！”
这时候，安慰她或者说一个自己的悲伤故事都不好。其实，这位姑娘的情绪要更加综合而复杂，她的真是情绪是，即为小乌龟的逝世感到
难过，又不想指责她的父亲。

***** 回答

“爸爸接下这个任务，说明他有男人的担当，但比起你来，缺乏一点女性的细致。看你这么伤心，天国的小乌龟不会责怪你的。”
这段话不仅给了这位姑娘情绪价值，也为我们内心构建了更为复杂的情绪回路。


***** 总结

人的记忆，从来都不是一栋完整的房子，到处是回忆的瓦 。情绪就像雨滴，当它淋在记忆的废墟上时，你会看到一个海市蜃楼的家，在
那个家里，有画满涂鸦的床头柜，有你曾经遗弃的小熊。进家拿起小熊，那种幻觉一般的触感，会让你找回过去的幸福，这份感觉会让你
不再沉默寡言，更不会歇斯底里。


** 情绪识别

你的情绪别人一定会察觉到，且受到你的情绪的影响。
放松的状态，无欲无求的状态是最自在的状态，能够最大的发挥自己的优点。
体会自己的感受，思想，从而去体会别人的思想。
一定要从别人身上体会其情感，观察其面部变化，才能提升自己的情感回路。

女人喜欢在她们面前很自在的男人，而且有魅力的男人都是这种在女人面前很自在的男人。
我内心的平静让女人在我身边时，感觉到安全。
情绪没有味道，但确实可以闻的到，你闻到某个人情绪的时候，你的内心也会自然升起那个情绪。
你所匮乏的会变成你所恐惧的，你一旦开始恐惧自己所匮乏的事物不能满足自己，你就会开始充满欲望。
每一个欲望背后都藏着一个深深的恐惧。
当注意力高度集中的时候，情绪，焦虑，和欲望都会消退，有人说男人在高潮的时候最接近神，其实是因为性爱的过程会高度集中人的注
意力。
这个世界上有很多事情需要等，但爱情这件事无需再等。

聊天时：不要说教，不要比较，不要评论，尽量少提问，尽量让语境变得轻松愉快一点。女生倾向于分享感受，很多话他们说出来没有目
的，就是想说而已，想分享一下此时此刻心里想到的而已。所以能和女生共鸣的对谈，必要的成分是分享感受。


** 感恩、知足

一定要懂得感恩和知足，关注那些美好的东西，让自己开心快乐起来。


** 自信

自信非常非常重要，beyand的歌曲中总会提到：打不死的自信心态活到老。
面试或者其他的重要场合，穿一身新衣服，你会不由自主的抬头挺胸，会更加有自信。


** 化一切尴尬于无形
黄勃：移花接木，反客为主；假痴不癫，以城动人。
*** 看破不说破
看破且说破，情商大忌。看破不说破，从来都不会让别人难堪。还能不着痕迹地化解尴尬，让人如木春风。
在自己能力范围内尽量做到极致和卓越。
