#+TITLE: 他山之石 
#+AUTHOR: 三石
#+DATE: <2017-11-18 Sat>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 


** 胜败

有时候，暂时的失利比暂时的胜利要好很多。 -- 《毛.骗》

体育中总是胜者不变，败者变。失败者会努力思考现状，改变修正不足，查找出奇制胜奇招，最终打败对手。当你失败的时候，可能是为
了让你拥有更大的成功。人生不如意事常八九，可我们却没有很好的接受失败教育。 -- 《白说》

1. First they ignore you. Then they laugh at you. Then they fight you. Then you win.


** 聪明

木秀于林，风必催之；堆出于岸，流比湍之；行高于人，人必非之。杨修和曹冲都是被自己的聪明害死的。

同时不叫的鹅被杀。应介乎才与不才之间

看破不说破；不痴不聋不做阿家翁；难得糊涂；等等都是古人的智慧，他们并非不知道，只是装糊涂，但绝不踩雷。这才是真聪明。

谁都不傻，但谁都有傻的时候。


** 比赛

比赛，骑自行车，总是许多人一起比赛时结果 *优于* 单独一个人去测试。

感觉这个可能和鲶鱼理论有某种程度上的关联。


** 量子纠缠

两个粒子相互纠缠，即使相距遥远，一个粒子的行为将会影响另一个粒子的状态。


** 策略
3. 《三侠五义》义渠人偷东西。《毛骗》第二季第六集44:22。第二季第八集19：11-23：58,27：55-29：59
4. 先让他失望，在给他希望，那样他就深信不疑。《毛骗》第一季，第二集,28:30
6. 当一个卧底都不知道自己是卧底的时候，自然毫无破绽。


** 思考

20. ego cogito ergo sum -- 我思故我在
14. A man is but the product of his thoughts what he thinks, he becomes.
28. silence is very import. 可以让自己好好思考总结考虑
11. 尘世的喧嚣比内心的不安更加不堪。有时需要拒绝接受外界的信息。


** 自信

1. Deeply believe in themselves.
1. 王侯将相宁有种乎 -- 陈涉世家
1. 做一些事情，让自己感觉有信心，然后推而广之，展现在生活的各个方面。
1. 我们的身体和心里是相互影响的。自信的坐姿，会让你变得自信。当感觉自己比周围人逊色很多的时候，假装自己很行，直到深入骨
   髓，这个和别人无关，只需要和自己的内心交流。最后会发现自己真的很厉害。 -- Amy Cuddy <TED>
1. 不自信的人说话的时候会关系别人，在意别人是否认同自己的话，是否自己在吹牛？但是自信的人，基本都是想时候什么说什么


** 潜意识

1. 如果你的潜意识不愿意做一件事情，那么你的潜意识会不知不觉让你做出损害这件事情的动作。所以一定要完全相信自己能够做到，
   否则自信的不足，会变成潜意识的阻碍。
1. 心里暗示：一种主观意识上被肯定的假设，不一定有根据。但是由于主观上已经肯定了他的存在，所以在心理上便竭力倾向这项内容。
1. 毕淑敏当兵在经过无人区时，背负 60 斤的东西行走了 120 里，期间认为自己坚持不下来，想自杀，但最终坚持了下来。最不可战胜
   的并不是我们的遭遇，而是我们内心是否坚强。


** 做

1. Next day tell me what you do differently not what a wonder day.
1. 我们明白了很多的道理，但是却过得不好，究其原因：我们只是知道，但是并没有去做。看到一句很有哲理的话，不光要感动，认为
   说的好有道理，最最重要的是去实践，Just Do IT！！！ NO FUCKING EXCUSES.
1. 纸上得来终觉浅，绝知此事要躬行 -- 陆游
1. It is difficult, if not impossible, for anyone to learn a subject purely by reading about it, without applying the
   information to specific problems and thereby being encouraged to think about what has been read. Furthermore, we all
   learn best the things that we have discovered for ourselves. -- Donald E. Knuth


** 刻意练习：

20. 成功成才需要多年刻意的练习。特定的目标；专注，不理会无关的事情；反馈；修正；走出舒适区；评价标准；行之有效的练习方法。
19. 对停止成长的节点保持警惕
17. 专注：其实是大脑在过滤其他不需要的东西。大脑前叶过滤的不好就无法专注。


** 时间
37. Life Calendar : 每周使用一个小方格，共 90 年。 格子数并不多，而且我们已经使用了很多。-- TED


** 拖延症
38. This long-term kind of procrastination that much less visible and less talked about than the funnier, short-term
    deadline-based kind. It usally suffered quietly and privately. And it can be the source of a huge amount of
    long-term unhappiness, and regrets.


** 选择

1. 选择太多，导致我们选择困难；我们会期望太高，难以满足；即使最终选择了一个很好的，也会认为自己放弃了某些美好的东西。
    [[https://open.163.com/movie/2017/7/9/P/MCNLQS3EQ_MCNLR7B9P.html][选择的困惑]] -- Barry Schwartz

1. 面对太多的选择，人们会变得麻木、被束缚。选择太难，我们总是会想明天再决定，可是一直是明日复明日
1. 即使从众多选择中选取了一个，我们也没有选择比较少的时候满意
   + 当我们对所选择的事物有一点点不满意的时候，就会后悔说是不是应该选择其他的，这会导致我们的不开心
   + 机会成本： 我们认为一个东西的价值的高低，取决于我们与之比较的事物。当有太多选择的时候，我们总是会去关注没有被选择的
     事物的优点，使你认为自己的选择美中不足。 *机会成本会让我们对自己的选择感到不满，即使我们的选择已经很好了* 。
   + 期望增加。当有太多的选择的时候，我们的期望会随之大大增加。幸福的秘诀：低期望
   + 面对众多选择，却仍然没有做好。我们会自我责备

鱼缸里面的鱼，可以在鱼缸里面做任何事情。但是任何事情不包括打破鱼缸，因为那将导致死亡，而不是自由。所以我们每个人都有一个
*不能去打破的鱼缸* 。


** 好的人际关系

1. There isn't time, so brief is life, for bickerings, apologies, heartburnings, calling to account. There is only time
   for loving, and but an instant, so to speak, for that. -- 马克吐温(马克吐温说：“生命如此短暂,我们没有时间去争吵、道歉、
   伤心、斤斤计较,我们只有时间去爱,一切稍纵即逝。”)
1. The good life is built with good relationships. -- 哈佛大学研究。好的人际关系和数量没有关系，质量很重要。自己会认为有一个真正可以依赖的人。
1. 像爱自己一样爱世上最平凡的人


** 规则

1. You obey all the rules and you lose all the funs.


** 常识

1. Common sense is not that common -- Voltaire "And this especilly appilies application."


** 冥想

1. deep breath 三个深呼吸
1. 各种形式的冥想都需要深呼吸，专注一件事情（任何事情都可以），发现无法专注时把自己拉回来。
1. The best learn is by tech.


** Fear

33. Fear is your friend. Fear is an indicator. Sometimes it shows you what you shouldn't do. More often than not it show
    you exactly what you should do. -- Timothy Ferriss
34. What's the worst that can happen?
35. Take the analytical frameworks, the capabilities you have, apply them to old fears. Apply them to very big dreams.
36. The frustration is not that they couldn't achieve their dreams, it's that they were not even able to start chasing
    them. -- TED
39. Deconstruct 解析-拆分 解构复杂问题的能力


** 珍惜现在

47. 我这辈子怎么好像没活过呀？一定一定不要到老了的时候说这样的话。
49. 人们总是在幸福的金马车已经驶过去很远，捡起地上的金鬓毛说，原来我见过她。


** 幽默
48. 幽默是一种生活的态度，这样就可以在任何时候找到化解尴尬的方法了。


** Rejection
1. In life, rejection is certain. Once you accept this fact, it will be easier to anticipate and to overcome moments of rejection.
2. Detach yourself from the results of a request, and you will become more confident and increase your chance for acceptance, or a "yes."
3. The worst part of rejection is the fear of it. Do not let the fear prevent you from making your request.
4. Rejection is nothing more than someone else's opinion. We should never consider it as truth about ourselves.
5. If we talk to enough people without giving up, a rejection will become an acceptance. 




** 学习

1. 为什么很多人宁愿忍受生活的苦，却不愿意承担学习的苦？ -- 网络文章
1. 学习的本质，不在于记住哪些知识，而在于她触发了你的思考 -- 迈克尔.桑德尔


** 杂项

1. 你嘴这么甜，你男朋友有糖尿病吧；你嘴这么毒，你男朋友有尿毒症吧。
1. friends. 第三季第十二集
1. 一个男人要保护好四样东西：脚下的土地，家里的父母，怀里的女人，身边的兄弟 -- 电影 《一路顺风》



** 主角

任何事做到极致就是艺术。这个世界上一百万人中只有一个主角，当主角的都是能够达到极致的人 -- 《无双》..画家


** 效率

效率 = *有用功* / 时间

盲目做一些没有意义的事情，即使很多，同样是效率低下。


** 系统

知识，关键是保护她的系统性；缺乏系统性就会很局限，难以做到全面和深入。


** rule

不要陷入教条主义。就像设计模式，应该理解其最终要达到的目的，而不是一味地生搬硬套。应该根据具体问题，灵活处理遇到的问题。

感觉都有点像具体问题具体分析了。


** 奖励

奖励会让人们唯奖励是图。孩子多读书，会得到奖励，会让孩子关心的只是书的厚度；依据学生升学率奖励老师，老师会只关系升学率
（只关系那些差一些就可以升学的学生）；


** 小说人物塑造

人物想的、说的、做的要不一样，比较容易塑造成功的人物。


** 窦文涛换电视

表演真听、真看、真体会以后，雄辩涛涛，将对方说的落泪，说的都崩溃。 *当人的情绪是真实的时候，它的力量是非常强大的* 

你知道不知道一个家庭，两个月没有电视看，是什么感觉呀？你知道吗？先生，如果是你，好像我这样，一个星期打电话，让我等两个星
期，一个星期打电话，让我等两个星期，现在已经两个月了，我有看电视的权利呀，我是一个人呀。尤其呢，这么大一部电视，日日在我
客厅，日日在我面前，就是打不开，你是什么感觉？你知不知到这对我的家庭生活产生多大的影响。

你莫同我吹泡泡了，你说几时？

激情的力量谁能挡？装的不行，得真的是被逼急了。感性的力量不容忽视。

往细了说，详细罗列关键点，说的有画面感或者既视感，让对方有共鸣。


** 本能和理性思考

1. 思考判断可能是动物最近几万年才进化出来的能力
1. 本能是动物进化几亿年的能力

有时候问题可能是需要本能解决


** 事情大小

某天遇到了一个天大的事情，以为天塌下来；然后睡一觉，第二天事情仍然在，但是心情会好很多。

所以事情大小，完全在自己怎么想


** 匠人精神

1. 食人之禄，忠人之事
1. 公司允许你粗制滥造，但是过不了自己这一关，自己做就要做到最好 -- 蒋文涛
1. 雇佣兵也可以打仗也可以卖命的
