#+TITLE: 美句
#+AUTHOR: 三石
#+DATE: <2018-03-25 Sun>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 


* 杂记

人们宁愿去关心一个蹩脚的电影演员的吃喝拉撒和鸡毛蒜皮，而不愿了解一个普通人波涛汹涌的内心......
---路瑶《平凡的世界》

世界上有两样东西不能直视，一是太阳，而是人心
---东野奎吾《白夜行》

人的恶，连佛都度不了
---《西游记》

一个人可以被毁灭，但不能被打败。
---海明威《老人与海》

生活就像一座围城，城里的人想出去，城外的人想进来。
---《围城》

其实所有纠结做选择的人心里早就有了答案，咨询只是想得到心里内心所倾向的选择，最终的所谓命运，还是自己一步步走出来的。
---东野圭吾《解忧的杂货铺》

让你难过的事，总有一天你会笑着说出来。
---《肖申克的救赎》

孩子，我要求你读书用功，不是因为我要你跟别人比成绩，而是，我希望你将来拥有选择的权利，选择有意义，有时间的工作，而不是被
迫谋生。当你的工作在你心中有意义，你就有成就感。当你的工作给你时间，不剥夺你的生活，你就有尊严。成就感和尊严，给你快乐。
---《亲爱的安德鲁》

真正有气质的淑女，从不炫耀她所拥有的一切，她不告诉人她读过什么书，去过什么地方，有多少件衣服，买过什么珠宝，因为她没有自
卑感。
---《圆舞》

十年饮冰，难凉热血。
---梁启超《饮冰室合集》

每逢你想要批评任何人的时候，你就记住，这个世界上所有人，并不是个个都有过你拥有的那些优越条件。
---《了不起的盖茨比》

我什么都没忘，只是有些事适合收藏。
---史铁生《我与地坛》

这是一个最好的时代，这是一个最坏的时代；这是一个智慧的年代，这是一个愚蠢的年代；这是一个光明的季节，这是一个黑暗的季节
---狄更斯《双城记》

被真相伤害总比被谎言欺骗的好，得到了再失去，总是比从来就没有得到更伤人。
---《追风筝的人》

也许每一个男子都有过这样两个女人，至少两个。娶了红玫瑰，久而久之，红的变成了墙上的一抹蚊子血，白的还是床前明月光。娶了白
玫瑰，白的便是衣服上沾的一粒饭粘子，红的却是心口上一粒朱砂痣。
---张爱玲《红玫瑰与白玫瑰》

庭有枇杷树，吾妻死之年所手植也，今已亭亭如盖矣。
---《项脊轩志》

哪有人喜欢孤独，不过是不喜欢失望罢了。
---村上春树《挪威的森林》

钱钟书先生对杨降，从今往后，咱们只有死别，再无生离。
---《我们仨》

对世界而言，你是一个人；但对于某个人，你是他的整个世界。
---《飘》

我知道我长的丑，被仍石头无所谓，但让你害怕让我觉得很难过。
---《巴黎圣母院》

海底月是天上月，眼前人是心上人。
---《我不喜欢这世界，我只喜欢你》

这世上真话本就不多，一位女子的脸红胜过一大段对白。
---《骆驼祥子》

I love three things in this world, Sun, moon and you, Sun for morning, moon for night, and you forever.
---《暮光之城》

山有木兮木有枝，心悦君兮君不如。
---《越人歌》

从前的日色变的慢，车马邮件都慢，一生只够爱一个人。
---木心《从前慢》

轻轻子衿，悠悠我心
---《诗经》

你下午四点钟来，那么从三点钟起，我就开始感觉幸福。时间越接近，我就越感到幸福。到了四点钟的时候，我就会坐立不安了
---《小王子》

偏见使我无法爱别人[微风][微风][微风]傲慢使别人无法来爱我
---《傲慢与偏见》

你走，我不送你；你来，再大的风我都要去接你。
---梁实秋《送别》

所有的大人都曾经是小孩，虽然，只有少数的人记得。
---《小王子》

为你，千千万万遍
---卡勒德.胡赛尼《追风筝的人》

如果你很想要一件东西，那么就放他离开，等他回来找你的时候，你就永远拥有他了。
---扶苏《哑舍》

爸爸的花儿落了，我已不是小孩子
---《城南旧事》

幸福的家庭都是相似的；不幸的家庭各有各的不幸。
---列夫托尔斯泰《安娜.卡列尼娜》

我们的社会为什么不能接纳同性恋者？因为我们的性文化里，把生育当做性的目的，把无知当纯洁，把愚昧当德行，把偏见当原则。
---柴静《看见》

任凭若水三千，我只取一瓢。
---《红楼梦》

她可以褪色，可以枯萎，怎样都可以，但只要我看她一眼，万般柔情便涌上心头。
---《洛丽塔》

许多年过去了，人们说陈年旧时可以被埋葬，而我终于明白这是错的，因为往事会自行爬上来。
---《追风筝的人》

要是爱你爱的少些，话就可以说的多些了。
---简.奥斯汀《傲慢与偏见》

只要你是天鹅蛋，就是生在鸡场也没有什么关系。
---《安徒生童话》

你千万别跟任何人谈任何事情。你只要一谈起，就会想念起每一个人来。
---《麦田里的守望者》

我慢慢地、慢慢地了解到，所谓父女母子一场，只不过意味着，你和他的缘分就是今生今世不断地在目送他的背影渐行渐远。你站在小路
的这一端，看着他逐渐消失在小路转弯的地方，而且，他用背影告诉你：不必追。
---龙应台《目送》

哭要一个人躲着哭，笑呢全世界陪你笑。
---《爱情之死》

如果你认识从前的我，那么你就会原谅现在的我。
---张爱玲《倾城之恋》

每当我追溯自己的青春年华时，那些日子就像是暴风雪之晨的白色雪花一样，被疾风吹的离我而去。
---《洛丽塔》

我把我的整个灵魂都给你，连同它的怪癖，耍小聪明，忽明忽暗，一千八百种坏毛病。它真讨厌，只有一点好，爱你。
王小波《爱你就像爱生命》

你不会遇到第二个我，友情也好，爱情也罢。
---《千与千寻》

如果喜欢谁，就满世界的找她，别等她来找你，她可能也在等你......别让她等的对你失望了。如果你喜欢的人要嫁人了，就跟她表白
一下，就算为此要把她婚车的车轴打爆也没什么，这是你说出来的最后机会，把这个秘密带进棺材没价值，连陪葬都算不上。
---楚子航《龙族》

嘿，你不必再等了，他不会回来了。
---《衷犬八公的故事》

“阿甘，你长大想成为什么样的人？” “什么，难道我不能成为自己吗？”
---《阿甘正传》

不是兄弟你不好，是这世道不干净，容不得你这样做人。
---施耐庵《水浒传》

我知道你回来，所以我在等。---沈从文《雨后》

人生的痛苦莫过于经历了风雨后，不但没有见到彩虹，还感冒了。

never say never!


* 《围城》

+ 不足两岁的孩子 :: 眼睛两条斜缝，眉毛高高在上，跟眼睛远隔得彼此要害相思病。
+ 孙太太 :: 忠厚老实人的恶毒，像饭里的沙砾或者骨鱼片里未净的刺，会给人一种不期待的伤痛。
+ 鲍小姐穿的少 :: 有人叫她"熟食铺子"，因为只有熟食店会把那许多颜色暖热的肉公开陈列；又有人叫她"真理"，因为据说"真理是赤
            裸裸的"。鲍小姐并未一丝不挂，所以他们修正为"局部的真理"。
+ 苏小姐的爱情观 :: 那时候苏小姐把自己的爱情看得太名贵了，不肯随便施与。现在呢，宛如做了好衣服，舍不得穿，锁在箱里，过一
             两年忽然发现这衣服的样子和花色都不时髦了，有些自怅自悔。
+ 饭菜不可口 :: 鱼像海军陆战队，已经登陆了好几天;肉像潜水艇士兵，会长期潜伏在水里。
+ 方鸿渐初见唐晓芙 :: 天生着一般女人要花钱费时，调脂和粉来仿造的好脸色，新鲜得使人见了忘掉口渴而又觉嘴馋，仿佛是好水果。
              她眼睛并不顶大，可是灵活温柔，反衬得许多女人的大眼睛只像政治家讲的大话，大而无当。方鸿渐看唐小姐不笑的时候，
              脸上还依恋着笑意，像音乐停止后袅袅空中的余音。许多女人会笑得这样甜，但她们的笑容只是面部肌肉柔软操，仿佛有
              教练在喊口令:"一!"忽然满脸堆笑，"二!"忽然笑不知去向，只余个空脸，像电影开映前的布幕。
+ 沈太太 :: 她眼睛下两个黑袋，像圆壳行军热水瓶，想是储蓄着多情的热泪。
+ 借褚慎明之口谈婚姻 :: 结婚仿佛金漆的鸟笼，笼子外面的鸟想住进去，笼内的鸟想飞出来。借苏文纨之口谈婚姻结婚是被围困的城堡，
               城外的人想冲进去，城里的人想逃出来。
+ 方鸿渐不情愿地吻苏文纨 :: 这吻的分量很轻，范围很小，只仿佛清朝官场端茶送客时的把嘴唇抹一抹茶碗边，或者从前西洋法庭见证
                 人宣誓时嘴唇碰一碰«圣经»，至多像那些信女们吻西藏活佛或罗马教皇的大脚指，一种敬而远之的亲近。
+ 方鸿渐被唐晓芙拒绝 :: 鸿渐身心仿佛通电似的发麻，只知道唐小姐在说自己，没心思来领会她话里意义，好比头脑里蒙上一层油纸，
               她的话雨点似的渗不进，可是油纸震颤着雨打的重量。他听到最后一句话，绝望地明白，抬起头来，两眼是泪，像大孩
               子挨了打骂，咽泪入心的脸。
+ 唐晓芙拒绝方鸿渐之后的心理 :: 可是心里忘不了他，好比牙齿钳去了，齿腔空着作痛，更好比花盆里种的小树，要连根拔它，这花盆
                   就得迸碎。
+ 曹元朗的朋友初见唐晓芙 :: 那个女孩子是"无忘我草"和"别碰我花"的结合，是红玫瑰变成了蔚蓝花-----"蔚蓝花"是浪漫主义遥远理
                 想的象征。
+ 方鸿渐失恋后 :: 有人失恋了，会把他们的伤心立刻像叫花子的烂腿，血淋淋地公开展览，博人怜悯，或者事过境迁，像战士的金疮旧
            斑，脱衣指示，使人惊佩。鸿渐只希望能在心理的黑暗里隐蔽着，仿佛害病的眼睛避光，破碎的皮肉怕风。
+ 赵辛楣公寓里放的无线电广播《春之恋歌》 :: 那女明星的娇声尖锐里含着浑浊，一大半像鼻子里哼出来的，又腻又粘，又软懒无力，
     跟鼻子的主产品鼻涕具有同样品性。可是，至少该有像鼻子那么长短，才包涵得下这弯绕连绵的声音。
+ 旅途中赵辛楣提到唐晓芙时，方鸿渐的心理 :: 鸿渐心里仿佛黑牢里的禁锢者摸索着一根火柴，刚划亮，火柴就熄了，眼前没看清的一
     片又滑回黑暗里。譬如黑夜里两条船相迎擦过，一个在这条船上，瞥见对面船舱的灯光里正是自己梦寐不忘的脸，没来得及叫唤，
     彼此早距离远了。这一刹那的接近，反见得暌隔的渺茫。
+ 李梅亭没戴眼镜 :: 李先生脸上少了那副黑眼镜，两只大白眼睛像剥掉壳的煮熟鸡蛋。
+ 下小雨 :: 仿佛许多小水珠在半空里顽皮，滚着跳着，顽皮得够了，然后趁势落地。雨越下越大这雨愈下愈老成，水点贯串作丝，河面
         上像出了痘，无数麻瘢似的水涡，随生随灭，息息不停，到雨线更密，又仿佛光滑的水面上在长毛。
+ 下雨之前的天气 :: 从早晨起，空气闷塞得像障碍着呼吸，忽然这时候天不知哪里漏了个洞，天外的爽气一阵阵冲进来，半黄落的草木
             也自昏沉里一时清醒，普遍地微微叹息，瑟瑟颤动，大地像蒸笼揭去了盖。
+ 雨天夜行，鞋子上的泥 :: 鞋子上的泥抵得贪官刮的地皮。
+ 雨后的路 :: 黄泥地面粘心硬，像夏天热得半溶的太妃糖，走路容易滑倒。
+ 李梅亭的衣着 :: 他的旧法兰绒外套经过浸湿烤干这两重水深火热的痛苦，疲软肥肿，又添上风瘫病;下身的裤管，肥粗圆满，毫无折
            痕，可以无需人腿而卓立地上，像一对空心的国家柱石;那根充羊毛的"不皱领带"，给水洗得缩了，瘦小蜷曲，像前清老人的辫子。
+ 车厢拥挤 :: 这车厢仿佛沙丁鱼罐，里面的人紧紧的挤得身体都扁了。可是沙丁鱼的骨头，深藏在自己身里，这些乘客的肘骨膝骨都像
          旁人的身体里硬嵌。罐装的沙丁鱼条条挺直，这些乘客都蜷曲波折，腰跟腿弯成几何学上有明目的角度。
+ 汽车夫骂汽车 :: 汽车夫愿意跟汽车的母亲和祖母发生肉体恋爱。
+ 饭馆 :: 桌面就像«儒林外史»里范进给胡屠户打了耳光的脸，刮得下斤把猪油。
+ 旅馆里的妓女 :: 这女人尖颧削脸，不知用什么东西烫出来的一头卷发，像中国写意画里的满树梅花，颈里一条白丝围巾，身上绿绸旗
            袍，光华夺目，可是那面子亮得像小家女人衬旗袍里子用的作料。说话又快又脆，像钢刀削萝卜片。
+ 侯营长 :: 侯营长有个桔皮大鼻子，鼻子上附带一张脸，脸上应有尽有，并未给鼻子挤去眉眼，鼻尖生几个酒刺，像未熟的草莓，高声
         说笑，一望而知是位豪杰。
+ 阿福 :: 这男人油头滑面，像浸油的枇杷核。
+ 饿 :: 鸿渐饿得睡不着，身子像没放文件的公事皮包，几乎腹背相贴，才领略出法国人所谓"长得像没有面包吃的日子"还不够亲切，长
       得像没有面包吃的日子，长得像失眠的夜，都比不上因没有面包吃而失眠的夜那样漫漫难度。
+ 烤山薯 :: 烤山薯这东西，本来像中国谚语里的私情男女，"偷着不如偷不着"，香味比滋味好，你闻的时候，觉得非吃不可，真到嘴，
         也不过尔尔。
+ 夜幕降临 :: 这是暮秋天气，山深日短，云雾里露出一线月亮，宛如一只挤着的近视眼睛。少顷，这月亮圆滑得什么都粘不上，轻盈得
          什么都压不住，从蓬松如絮的云堆下无牵挂地浮出来，原来还有一边没满，像被打耳光的脸肿着一边。
+ 孙柔嘉哭 :: 她像睡着了，脸上泪渍和灰尘，结成几道黑痕; 幸亏年轻女人的眼泪还不是秋冬的雨点，不致把自己的脸摧毁得衰败，只
          像清明节的梦雨，浸肿了地面，添了些泥。
+ 科学和科学家 :: 科学家跟科学大不相同。科学家像酒，愈老愈可贵，而科学像女人，老了便不值钱。
+ 高松年 :: 高校长肥而结实的脸像没发酵的黄面粉馒头，"馋嘴的时间"咬也咬不动他，一条牙齿印或皱纹都没有。
+ 撒谎 :: 撒谎往往是高兴快乐的流露，也算得一种创造。一个人身心舒畅，精力充沛，会不把顽强的事实放在眼里，觉得有本领跟现状
        开玩笑。
+ 丑 :: 中国人丑得像造物者偷工减料的结果，潦草塞责的丑，西洋人丑像造物者恶意的表现，存心跟脸上五官开玩笑，所以丑得有激化，
       有作用。
+ 缺点（高松年） :: 一个人的缺点正像猴子的尾巴，猴子蹲在地面的时候，尾巴是看不见的，直到他向树上爬，就把后部供大众瞻仰，
             可是这红臀长尾巴本来就有，并非地位爬高了的新标识。
+ 说话 :: 我们在社会上一切说话全像戏院子的入场券，一边印着"过期作废"，可是那一边并不注明什么日期，随我们的便可以提早或延
        迟。
+ 汪处厚的胡子 :: 又稀又软，挂在口角两旁，像新式标点里的逗号，既不能翘然而起，也不够飘然而袅。
+ 范小姐惊骇的表情 :: 惊骇像牙医生用的口撑，教她张着嘴，好一会上下腭合不拢来。
+ 鸡汤太淡 :: 这不是煮过鸡的汤，只像鸡在里面洗过一次澡。
+ 闲话 :: 两个人在一起，人家就要造谣言，正如两根树枝相接近，蜘蛛就要挂网。
+ 上司驾驭下属 :: 西洋赶驴子的人，每逢驴子不肯走，鞭子没有用，就把一串胡萝卜挂在驴子眼睛之前，唇吻之上。这笨驴子以为走前
            一步，萝卜就能到嘴，于是一步再一步继续向前，嘴愈要咬，脚愈会赶，不知不觉中又走了一站。那时候它是否吃得到这串
            萝卜，得看驴夫的高兴。一切机关里，上司驾驭下属，全用这种技巧。
+ 天下只有两种人 :: 譬如一串葡萄到手，一种人挑最好的先吃，另一种人把最好的留在最后吃。照例第一种人应该乐观，因为他每吃一
             颗都是吃剩的葡萄里最好的;第二种人应该悲观，因为他每吃一颗都是吃剩的葡萄里最坏的。不过事实上适得其反，缘故是
             第二种人还有希望，第一种人只有回忆。从恋爱到白头偕老，好比一串葡萄，总有最好的一颗，最好的只有一颗，留着做
             希望，多少好?
+ 请客吃饭 :: 请吃饭好比播种子:来的客人里有几个是吃了不还请的，例如最高上司和低级小职员;有几个一定还席的，例如地位和收入
          相等的同僚，这样，种一顿饭可以收获几顿饭。
+ 领导去办公室 :: 一切机关的首长上办公室，本来就像隆冬的太阳或者一生里的好运气，来得很迟，去得很早。
+ 回家 :: 回家只像半生的东西回锅，要煮一会才会熟。
+ 方鸿渐和孙柔嘉吵架 :: 她仿佛跟鸿渐抢一条绳子，尽力各拉一头，绳子迸直欲断的时候，她就凑上几步，这绳子又松软下来。气头上
               虽然以吵嘴为快，吵完了，他们都觉得疲乏和空虚，像戏散场和酒醒后的心理。
+ 方鸿渐懊悔回到上海 :: 就是条微生虫，也沾沾自喜，希望有人搁它在显微镜下放大了看的。拥挤里的孤寂，热闹里的凄凉，使他像许
               多住在这孤岛上的人，心灵也仿佛一个无凑畔的孤岛。
+ 辞职 :: 在一切机关里，人总有人可替，座位总有人来坐，怄气辞职只是辞职的人吃亏，被辞的职位漠然不痛不痒;人不肯坐椅子，苦
        了自己的腿，椅子空着不会肚子饿，椅子立着不会腿酸的。
+ 鸿渐吵架后，在饥饿中入睡 :: 最初睡得脆薄，饥饿像镊子要镊破他的昏迷，他潜意识挡住它。渐渐这镊子松了，钝了，他的睡也坚实
                  得镊不破了，没有梦，没有感觉，人生最原始的睡，同时也是死的样品。


* 怦然心动

Some of us get dipped in flat, some in satin, some in gloss. But every once in a while you find someone who's
iridescent, and when you do, nothing will ever compare. 
有些人沦为平庸浅薄，有些人光鲜亮丽，有些人金玉其外，而败絮其中。可不经意间，有一天你会遇到一个彩虹般绚丽的人，从此以后，
其他人就不过是匆匆浮云。

A painting is more than the sum of its parts. A cow by itself is just a cow. A meadow by itself is just grass, flowers. 
And the sun peeking through the trees is just a beam of light. But you put them all together and it can be magic.
一幅画不是众多物件简单拼凑而成的。牛只是一头牛，草地也只是青草和鲜花，而穿过树枝的阳光也仅仅只是一束光，但如果将他们方法
放到一起，就会产生魔一般的魅力。

The higher I got, the more amazed I was by the view.
我爬的越高，眼前的风景便愈发迷人。

Some days the sunsets would be purple and pink. And some days they were a blazing orange setting fire to the clouds
on the horizon. It was during one of those susets that my father's idea os the whole being greaater than the sum of its
parts moved from my head to my heart.
有时落日泛起紫红的余辉，有时候散发出橘红色的火光燃起天边的晚霞。在这绚烂的日落景象中，我慢慢领悟了父亲所说的整体胜于局部
总和的道理。

Sometimes a little discomfort in the beginning can save a whole lot of pain down the road.
有时起初的隐忍可以避免一路的疼痛。

The first day I met Bryce Loski, I flipped. It was those eyes, something in those dazzling eyes.
见到布莱斯.罗斯基的第一天，我心动了。他的双眸有种魔力让我如痴如醉。

The next thing I know, he's holding my hand and looking right into my eyes. My heart stopped. Was this it? Would this be
my first kiss?
接下来，我所知道的就是，他紧紧握住我的手，与我深情对视。我的心跳停止了。就要来了吗？我的初吻就要来了吗？

Well, a girl like that doesn't live next door to everyone.
这种女孩可是可遇不可求的。

And I realized Garrett was right about one thing: I had flipped. Completely.
我意识到加利特一件事说对了：我心动了。完全心动了。


* 郭德纲

说话不清，钝刀杀人

饥餐渴饮，晓行夜宿

