#+TITLE:        哈弗幸福公开课
#+AUTHOR:       三石
#+DATE:         <2017-11-18 Sat>
#+EMAIL:        kyleemail@163.com
#+DESCRIPTION: 
#+TAGS:         幸福
#+CATEGORIES:   


内容比较凌乱，待系统学习，梳理脉络，整理提纲 TODO

并不是所有的心理学观点或者研究都适合你，选择合适自己的去实践很重要。。。

** 为什么要研究积极心理学？

+ 需要集中研究，这样会带来更大的收获
+ 并不是治疗了抑郁等负面情绪，就会变得幸福快乐
+ 积极心理学可以有效预防压抑、

Questions always create reality. 我关注什么就只会看到什么。游戏：限定时间内观察一幅画，问题画中有多少几何图形？时间到后，
大多数人只会数几何图像的个数。如果再问，图中钟表的时间？大巴车中有几个孩子？图像左侧主要的颜色？等这些问题时，几乎没有人
知道。

We see what we look for and we miss much of what we are not looking for even though it is there... Our experience of the
world is heavily influenced by where we place our attention. --- Stavros and Torres

resilience :: 即使面对糟糕的环境、恶劣的处境，仍旧保持乐观、对未来充满希望。不是那种盲目乐观，而是这次没有成功、总结经验，
相信下次定会成功。

+ 认清长处
+ 设立目标
+ 榜样 role model
+ 不单干，社会支持

欣赏优点、美好的东西也很重要。

appreciate：欣赏长处、成功。不应把其视为理所当然；成长，欣赏长处-采取行动-长处增长；

责任：为了让小组变得更加美好，我能做什么？而不是去抱怨那个人哪里做的不够好等等

No one is coming! 你只能自救，没有什么超级英雄可以帮助你，给你制造一个乐园。你只能自己努力。

关注优点，而不是仅仅去改善缺点，会更加成功。

comfortably numb 舒适的麻木

+ 健康模型：我之所以生病，是因为我们不够健康，怎样才能健康呢？追求有意义的生活，追求生活目标，做真正有意义的事情，找到自
  己 passion 所在，好的人际关系等等，这样我们就会健康；
+ 疾病模型：将疾病治好，我们就健康了；

我们拥有强大的免疫系统，并不是我们不再生病，而是我们更少生病，而且生病时能够更好的处理。

+ 搭建桥梁 :: 专业研究与实际生活之间的桥梁
+ change is possible :: 个人或者组织等都是可以改变的，会有相应的技巧、工具、方法
+ 理性和感性看待这个世界 :: 怎样处理不好的周遭环境
+ 顺从人性，接受其所有缺点和优点 :: 而不是从心里层面上改善他
+ 更高的道德追求 :: 幸福并不是我们的终结追求，还有更高级、高尚的追求

务实的理想主义者：必须要结合理论去实践，而不是盲目去做，否则可能只会带来伤害或者失败！

改变是可能的，如创伤性应激障碍 PTSD；

不应该只是去研究平均值，而是应该去研究那些最成功的一些人，那些最幸福的一些人，从而才能更好的得到规律

研究那些顶尖人员，那些精英，这样我们普通大众才能更好的向这些精英学习，来提高自己。否则只是研究平均，得到的结果将人类的潜
能大大削弱。同样也应该研究我们个人最成功、最开心、最好的恋爱关系，从中学习，应用到生活的其他方面。曼哈顿计划就是聚集了一
些精英，让他们一起创造出了原子弹。 

*将杰出大众化* 。人们总是低估了自己改变的能力。

外在的因素很难改变我们，比如是否获得终身教授、是否得到彩票，找到理性的生活伴侣。对一个人的影响都是暂时的，一段时间之后，
他们仍然会恢复到之前的快乐水平。财富对一个人是否幸福，影响甚微（当然是在满足了基本的需求之后）。我们比父辈要富裕，比祖父
辈更加富裕，但是幸福并没有增加，而且这是一个全球性的问题。

我们的幸福主要取决于我们的内心。


** 失败

我们的免疫系统会在得病之后获得相应的抗体，而我们的心里层面也是一样。失败也会给我们的心里增加抗体，我们应该多多经历一些失
败，这将很有助于成功（失败的作用总是被低估了）

每天早上告诉自己，我最棒、我最棒、我最棒，我是这个世界上最聪明的人，经常有老师刻意夸奖自己做的很好，只有积极的言论（无论
是外部还是内部）是没有用的，可能还是有害的。 Rather than talk, we need action. 努力去做，我们将比原来更成功，为这将给我
们自信，反过来友会让我们更加成功。


** vmisualize

当我们看到自己的左手的时候，大脑的某些神经元会兴奋，另外当我们闭上眼睛，想象自己的左手的时候，同样的神经元会兴奋，我们的
大脑无法区分，这是真实的还是想象的。这也是我们无法区分是否在做梦的原因。 Visualize your journey of getting there, as
well as the destination ifself. 想象成功，同时想象为了成功而努力的过程，单纯只想象成功效果并不好。 《secret》 一书中也提
到了相似的观点，想象自己已经得到的希望的事物（视动行为复演法）。
