#+TITLE:          Positive Psychology
#+AUTHOR:         Kyle Three Stones
#+DATE:           <2018-12-02 Sun>
#+EMAIL:          kyleemail@163.com
#+OPTIONS:        H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t f:t tex:t
#+TAGS:           幸福公开课
#+CATEGORIES:     


** 为什么需要积极心理学

1. 需要集中研究，带来更大的收货
1. 并不是治愈了抑郁，就会快乐
1. 积极心理学可以有效预防压抑等



** Question very often create reality

测试实验：30 s 观察一幅画，问这幅画中有多少个几何图形？那么在这 30 S 内，测试者会进全力去数这幅画的几何图形的个数，但是
由于这幅画里有太多太多的几何图形，被测试者在有限的 30s 内根本没有办法数过来。而再给这些测试者提问。图片上的大巴里面有几
个孩子？左下角的钟表的时间是几点？右侧的颜色？几乎没有几个人知道。

这种注意力可以帮助我们投入到一件事情上，但是如果只是给自己提问这一个问题，那么我们忽略其他。

生活中，大多数人会问自己什么问题。我的缺点是什么，有什么不足？这没有什么不对，但是，如果我们只是给自己提问这一个问题，我
们会忽略掉我们的优点，我们将只能看到自己的缺点。again，question create reality.

Stavros and Torres 一本关于婚姻的书中说：We see what we look for and we miss much of what we are not looking for even
though it is there. Our experience of the world is heavily influenced by where we place our attention.


** 冥想

1. 专注一件事情：动作、姿势、呼吸、同情心、爱、善心、火焰等等都可以
1. 基础：深呼吸 deep breathing ，腹部呼吸
1. 锻炼：集中-分心-集中-分心... 从而更留心专心

冥想时没有目的。

《改善情绪的正念疗法》

The mindful way through depression.

三个深呼吸


** 积极养成

1. 把积极的东西记录到日记中，慢慢培养成习惯，模式。搜寻生活中有趣的东西。


** 心理弹性

即使面对不好的环境，仍旧很乐观。不是那种盲目的乐观，而是这次没有成功，总结经验，相信下次会成功。

他强任他强，清风拂山岗，他横任他横，明月照大江。他自狠来他自恶，我自一口真气足。 -- 《倚天屠龙记》

1. 认清长处
1. 设立目标
1. 榜样
1. 不单干，社会支持

行动让自己乐观，从而也更容易成功。

责任：我有什么贡献，可以让小组变得更好？我能做什么

No one is comming! 你只能自救。It is up to you to success.

Marva Collins 很有影响的黑人女性老师。


适合自己的最重要。

生命不息，学习不止。
