#+TITLE: 自我完善 
#+AUTHOR: 三石
#+DATE: <2017-11-18 Sat>
#+EMAIL: kyleemail@163.com
#+DESCRIPTION: 


** 自信、乐观开朗、有活力、笑

+ 自信打不死的心态活到老。
+ 凡事都要有自信。展现在生活的方方面面。
+ 不要低声下气。
+ 对未来乐观、有热情。
+ It is not the strongest of the species that survives nor the most intelligent. It is the one that is the most adaptable to change. -- Charles Darwin
+ 要多笑，这么多年的牙可别白刷了
+ You got a dream, you gotta protect it. People can't do something themeselves, they wanna tell you you can't do it. If
  you want something, go get it. Period. -- The pursuit of happiness
+ 我父亲说，生活很简单的，如果你非常想得到什么，你就会得到。而失败只是表明，欲望还不够 -- 理发师的情人


** 思考

+ ego cogito ergo sum -- 我思故我在
+ 必须要自己思考，形成自己的观点。
+ 行成于思，毁于随。


** 技巧-策略

谋定而后动，知止而有得，凡事讲究策略；plan A 还要有 plan B


** 想法-行动

TED -- Mel Robbins : 5 秒法则

1. 当你有一个想法（想要去结交一位异性、想要在 party 上面跳舞、想要去健身），如果你没有在 *5S* 内去做，你就会放弃你这个想
   法。
1. 大脑运作很快，可以在 33 毫秒内处理一个面部表情。如果你没有即使行动，大脑会去处理其他事情。
1. *强迫* 自己走出舒适圈。所有不是你平时一直在做的事情（自动驾驶模式），都需要你强迫自己。
1. Do not follow what you fell, follow what you want.
1. 你可以做任何你想做的事情。 It is simple, but not easy. 
1. Stop saying I'm fine
1. Get outside. 就是开始去做


** 我要喜欢你

与人交往的秘诀就只有五个字：我要喜欢你 -- 卡内基

+ 像爱自己一样爱世上最平凡的人
+ 始终站在对方的立场，凡是为对方考虑。


** 我是一个蠢货

+ 凡事不要去太多顾及自己的脸面，害怕丢人现眼。这样会在反复思考后放弃很多的机会。想做就去做。想到就去做
+ I am a muttonhead, cretin, dumbbell, imbecile.
+ I just don't embarrass that easily. -- Rachel


** practise

不要太高估天赋的作用。只要坚持学习、练习，你肯定能成功。


** 动机

必须保持强大的动机才能坚持去做一件事。


** 感动自己才能感动别人

你做的事情或者事物自己都没有感觉多牛，怎么可能打动其他人。


** 曾国藩六戒-五勤

六戒
1. 久利之事勿为，众争之地勿往
2. 勿以小恶弃人大美，勿以小怨忘人大恩
3. 说人之短乃护己之短，夸己之长乃忌人之长
4. 利可众而不可独，谋可寡而不可众
5. 天下古今之庸人，皆以一懒字致败；天下古今之才人，皆以一傲字致败
6. 凡办大事，以识为主，以才为辅；凡成大事，人某居半，天意居半

五勤
7. 身勤
8. 眼勤
9. 手勤
10. 口勤
11. 心勤
业精于勤荒于嬉


** Parkindon's law

The perceived complexity of a task will expand to fill the time you allot it.


** 80 - 20 法则

80% 的成果源自 20% 的努力


** 目光放长远

不要只计较一时的得失。一切朝最终目标看齐。

做一个务实的理想主义者。


** Never say never

1. 永不言败，永不放弃
1. 坚持下去，并不是我们真的足够坚强，而是我们别无选择 -- 丘吉尔


** 口才
*语言的魅力是无穷的* -- 

可以和朋友谈一些自己的伤心往事失败生活，这样才能拉近彼此的关系。
如果只是谈论自己的成功，只会与对方产生更大的距离。


** 选择比努力更重要

像下棋一样，看到一步以后的变化已不易，看到三步，十步之后何其难也。
另外，像自己这样的平凡人，往往一开始并不知道自己将来要做什么。
当自己不清楚要做什么的时候，应该追求优秀，把眼下的事做到最好。
一直追求优秀，拼命提升自己，新的平台出现时，自然会有新的方法，而且你的优秀让你的选择多了很多。
当我们没有那么高瞻远瞩的时候，不妨着眼当下，而不是纠结选择和规划，白白错失提升自己的大号时光。


** 时间

I truly believe this, there is time. Even if we are busy, we have time for what matters. 
And when we focus on what matters, we can build the lives we want in the time we've got.
一周有 *24 * 7 = 168* 小时，8 * 5 = 40 小时上班，8 * 7 = 56 小时睡觉，应然剩余 *62* 小时。


** 自成体系
就像李小龙熟练掌握叶问的咏春拳，明白咏春拳的缺点，然后自行创建了截拳道。蒋甲的100天被拒绝之于加拿大人的被拒疗法。牛人总
是可以将知识融汇贯通、自成体系；而不仅仅是吸收知识。


** 享受追求的过程

生活需要目标，需要奋斗，需要不断的努力。在一直仰望目标的时候，不要忘记享受追寻的过程。如果只是在最后得到的时刻才感到开心
快乐，那生活将注定无趣的多，况且最终还不一定会成功。生活不能活成压缩饼干。要享受你追寻目标的过程，为生活的小成就而欢呼。

同时也要做一些看似无用的事情，练练素描，学学电子琴，听听古典音乐，努力锻炼身体等等。总之不用功利性太强，这些看似无用的东
西，将来可能有大用。 -- 白岩松 《白说》

那些有成就的人，通常都是很有趣的人。他们会享受生活，所以更有可能创造出好的产品。

那些感觉工作没有意思的人，肯定是没有将心思放在工作上。一旦将心思投入到工作中，肯定会感觉有意义，会有成就感。


** 努力

吴军的浪潮之巅书中描述，硅谷那些创业初期的员工每周工作 80， 90 甚至 100 小时，其在谷歌工作时，晚上 12:00 修改完代码提交
以后回去休息，但其上级仍然要工作到更晚。

经理说其在华为的时候，每天晚上 12:00 要开会，都要工作到晚上 2:00 左右，第二天正常上班。我开始还以为很夸张，现在看来，这
应该是真的。

想想自己，总以为自己牺牲了很多的休息时间，去学习。可是和他们差距真的是太远了。


古人学问无遗力，少壮工夫老始成。纸上得来终觉浅，绝知此事要躬行。 -- 陆游 《冬夜读书示子聿yu》

只有及其努力，才能看起来毫不费力 -- 刘同

We suffer more often in imagination than in reality. -- Seneca



** 学习

It is difficult, if not impossible, for anyone to learn a subject purely by reading about it, without applying the
information to secific problems and thereby being encouraged to think about what has been read. Furthermore, we all
learn best the things that we have discovered for ourselves. -- Donald E. Kunth

1. 和“纸上得来终觉浅，绝知此事要躬行”一个道理吧！
1. 基础很重要，就是武侠小说中的内功；一定要好好阅读《深入理解计算机操作系统》这本书
1. 认真仔细看完一本书，而不是草草看完 100 本书；如果没有好好掌握书中的知识点，那么等于没有阅读，还浪费了时间
1. 正确的思考和学习习惯非常非常非常重要，这个直接决定所有事情的成败；一个优秀的教练可以很好交给你
1. 专注 focus


** 不揭别人伤疤

Joly 说 Even if I'm wrong, who cares? Just be a friend, okey? Be supportive.


** 影视深刻影响思维

自己所看的娱乐节目、电影、电视，都会深刻的影响自己的思维。记得《怪诞心理学》那本书上写着，即使说一句“老人的皮肤是褶皱的”
这么一句话，都会让测试者的步伐变得缓慢。TED 上有人演讲说看黄色视频导致了男尊女卑、性暴力等问题，经常看将深刻改变我们的思
维。所以 *一定一定拒绝接受那些没有营养的东西* 。


** 今天

你的一生都是有无数个今天组成的， *如何度过今天，将会如何度过一辈子* 。

1. 每天完成一件事情，当别人问及今天做了什么，可以回答的形式
1. 一次只做一件事情，做好了再去做第二件事情


** 目标-关键成果-热情

Objectives & Key results 目标是方向，关键成果需要评估，做到了或者没有，简单明了。目标是想要做什么，即 what ，关键成果是
如果做成这件事，即 How 。

设定目标时，要知道 why ，将自己的 passion 和 objective 结合，将产生奇迹。

细心设定一个目标，并年复一年的去实现。

可悲的是自己居然并没有目标。 Fight for what is really matters.


** 庞氏骗局

谨防各种形式的庞氏骗局。当利润率高于 15% ，就一定要想想，这个很可能不合理。


** half the time, half the cost

时间直接决定成败


** You Can

大多数人认为自己根本不会绘画，但是 Granam Shaw 在 TED 上的演讲，在几分钟内便教会了人们画漫画的技巧。可见你并不是真的不能，
只是没有去做而已。很多其他的事情同样如此，你可以做到，只是你不知道自己可以做到，同时也没有去做而已。

视频地址： [[https://open.163.com/movie/2016/6/E/B/MBP8C1QF8_MBPPPA9EB.html][凭什么你认为自己不会画画？]]


** 活着的意义

亚马逊上有 151928 本书在教会人们活出生活的意义。

1. who you are ?
1. what you do ?
1. who you do it for ?
1. what those people want and need ?
1. how they change as a result ?

自己是做什么的？自己喜欢做什么？你最擅长什么，可以达到能教别人的程度？


** 预先思考

人类在特殊环境下会丧失一部分能力，比如在森林遇到狮子，你不会再有爱美之心、性欲等等。但你需要逃跑的能力，需要理智和逻辑。
此时面对压力，可能无法很好的处理，所以你需要 *预先思考* 。假如遇到什么事情，我应该怎样去做。

1. 把易丢失的物体，放到固定的位置，就会很容易找到。钥匙，固定放在门口的碗里，手机固定放在桌子右上角，护照固定放在第三个
   抽屉等等。
1. 让思维处理事情的方式固定下来，这样就会很容易处理


** 简单的才是最好的

1. 最简单可靠的方法才是最好的方法
1. Keep it simple, stuped.
1. 什么是统计密集场所人数的好方法？摄像头（依赖复杂的算法）？一个印度小朋友在 TED 上演讲说使用一个铺在地上的传感器，数步
   数来统计，突然感觉这个好简单，而且也会很准确。
1. 大道至简


** 一辈子只做一件事

一辈子只有认真做好一件事情就好了。


** 清楚的知道自己想要什么

Know what you want!!!!

对于想要的尽全力追求；不想要的不要分心，也不要有任何幻想。


** 追求

追求一件事情的过程很辛苦漫长，常常看不到目的地在何方。最近在解 bug 的时候，突然有相似的感觉，开始茫无目的，一点点的跟踪，
不是这里的问题，不是这里的问题，慢慢发现可疑点，继续追踪，很快发现是这里一个地方处理有一点小问题，修改之后，功能正常。


** 抛开一切你想干什么

抛开工资、抛开前景、抛开经济，你想干什么？


** 做一个优秀的普通人

*有破产的公司，没有倒闭的人* 。认认真真做好自己的每一个件事情：打扫房间的清洁工，仔细打扫；犹太人砌自己监狱的墙也砌的特
别整洁；交代别人一件事情的时候，尽量替别人考虑（到西二旗大概得多久？答：走路大概半个小时，但是早高峰可能要 20 分钟才能进
站，从西二门进可能人比较少）； *这就是一个人的习惯* 。

台湾首富王永庆买米，帮人家跳掉米中的砂石，帮人家送货到家，将米缸中的陈米导出来，新米放进去，然后再放入陈米。

我说了并等于你听到了，你做了并不等于你做到了。


** 自己的小作坊

满足自己的现状，一直做下去。不太在意投入产出比。不要一直想更多、更多，不要被业绩追着跑。


** 玩游戏

人生不是玩游戏，几乎没有 replay 的机会。一旦试错，可能几年后很难重新入场。


** 非走不可的弯路

不像清华北大的学生，三本学生，上升空间很小，但是又不甘心，只能屡屡的跳槽

如何工作？如何与同事相处？如何如果表达自己的想法？如何听懂别人的意思？


** 熬年头

现在的社会已经不是熬年头就可以了。

现在社会上需求度最多的十个工作，在十年前都没有出现过。


** 艺术

任何事情做到极致都是艺术 -- 《无双》


** 体贴-聪明-风趣

努力的方向


** 先思考-后动手

任何事情都需要两次创造，一次在大脑，一次在时间 -- 《高效能人的七个习惯》


** 情绪

1. 有情绪后，先暂缓 12 秒
1. 搞清楚情绪的根源，你到底因为对方说谎，还是因为
1. 权衡利弊，事已至此，骂对方一顿，于人于己有好处吗？
1. 疏导情绪，记日记（详细），音乐，运动，倾诉
